-- Generated by the Organizer Library (Sun Nov 16 12:49:48 2025)
return {
    [1]={
        ["log_name"]="debahocho +1", 
        ["id"]=21924, 
        ["name"]="debahocho +1", 
        ["count"]=1
    }, 
    [2]={
        ["log_name"]="defending ring", 
        ["id"]=13566, 
        ["name"]="defending ring", 
        ["count"]=1
    }, 
    [3]={
        ["log_name"]="null belt", 
        ["id"]=26367, 
        ["name"]="null belt", 
        ["count"]=1
    }, 
    [4]={
        ["log_name"]="rao sune-ate +1", 
        ["count"]=1, 
        ["id"]=27379, 
        ["name"]="rao sune-ate +1", 
        ["augments"]={
            [1]="Pet: HP+125", 
            [2]="Pet: Accuracy+20", 
            [3]="Pet: Damage taken -4%"
        }
    }, 
    [5]={
        ["log_name"]="samnuha tights", 
        ["count"]=1, 
        ["id"]=27295, 
        ["name"]="samnuha tights", 
        ["augments"]={
            [1]="STR+10", 
            [2]="DEX+10", 
            [3]="\"Dbl.Atk.\"+3", 
            [4]="\"Triple Atk.\"+3"
        }
    }, 
    [6]={
        ["log_name"]="null loop", 
        ["id"]=26042, 
        ["name"]="null loop", 
        ["count"]=1
    }, 
    [7]={
        ["log_name"]="gavialis helm", 
        ["id"]=26702, 
        ["name"]="gavialis helm", 
        ["count"]=1
    }, 
    [8]={
        ["log_name"]="rawhide gloves", 
        ["count"]=1, 
        ["id"]=27100, 
        ["name"]="rawhide gloves", 
        ["augments"]={
            [1]="Mag. Acc.+15", 
            [2]="INT+7", 
            [3]="MND+7"
        }
    }, 
    [9]={
        ["log_name"]="earthcry earring", 
        ["id"]=11037, 
        ["name"]="earthcry earring", 
        ["count"]=1
    }, 
    [10]={
        ["log_name"]="sroda ring", 
        ["id"]=26221, 
        ["name"]="sroda ring", 
        ["count"]=1
    }, 
    [11]={
        ["log_name"]="hermes' sandals +1", 
        ["id"]=11380, 
        ["name"]="hermes' sandals +1", 
        ["count"]=1
    }, 
    [12]={
        ["log_name"]="anwig salade", 
        ["id"]=11488, 
        ["name"]="anwig salade", 
        ["count"]=1
    }, 
    [13]={
        ["log_name"]="goldsmith's ring", 
        ["id"]=15821, 
        ["name"]="goldsmith's ring", 
        ["count"]=1
    }, 
    [14]={
        ["log_name"]="herculean trousers", 
        ["count"]=1, 
        ["id"]=25842, 
        ["name"]="herculean trousers", 
        ["augments"]={
            [1]="Pet: Accuracy+28 Pet: Rng. Acc.+28", 
            [2]="Pet: \"Store TP\"+11"
        }
    }, 
    [15]={
        ["log_name"]="karagoz earring +1", 
        ["id"]=25523, 
        ["name"]="kara. earring +1", 
        ["count"]=1
    }, 
    [16]={
        ["log_name"]="rao haidate +1", 
        ["count"]=1, 
        ["id"]=27203, 
        ["name"]="rao haidate +1", 
        ["augments"]={
            [1]="Pet: HP+125", 
            [2]="Pet: Accuracy+20", 
            [3]="Pet: Damage taken -4%"
        }
    }, 
    [17]={
        ["log_name"]="balder earring +1", 
        ["id"]=26115, 
        ["name"]="balder earring +1", 
        ["count"]=1
    }, 
    [18]={
        ["log_name"]="stone gorget", 
        ["id"]=13177, 
        ["name"]="stone gorget", 
        ["count"]=1
    }, 
    [19]={
        ["log_name"]="fotia gorget", 
        ["id"]=27510, 
        ["name"]="fotia gorget", 
        ["count"]=1
    }, 
    [20]={
        ["log_name"]="magoraga bead necklace", 
        ["id"]=11627, 
        ["name"]="magoraga beads", 
        ["count"]=1
    }, 
    [21]={
        ["log_name"]="null masque", 
        ["id"]=24270, 
        ["name"]="null masque", 
        ["count"]=1
    }, 
    [22]={
        ["id"]=10963, 
        ["name"]="airmid's gorget", 
        ["count"]=1, 
        ["log_name"]="airmid's gorget"
    }
}