-- Generated by the Organizer Library (Sun Mar 16 01:01:59 2025)
return {
    [1]={
        ["log_name"]="solemnity cape", 
        ["id"]=26245, 
        ["name"]="solemnity cape", 
        ["count"]=1
    }, 
    [2]={
        ["log_name"]="moonlight cape", 
        ["id"]=26269, 
        ["name"]="moonlight cape", 
        ["count"]=1
    }, 
    [3]={
        ["log_name"]="null shawl", 
        ["id"]=26274, 
        ["name"]="null shawl", 
        ["count"]=1
    }, 
    [4]={
        ["log_name"]="cichol's mantle", 
        ["count"]=1, 
        ["id"]=26246, 
        ["name"]="cichol's mantle", 
        ["augments"]={
            [1]="DEX+20", 
            [2]="Accuracy+20 Attack+20", 
            [3]="Accuracy+10", 
            [4]="\"Dbl.Atk.\"+10", 
            [5]="Phys. dmg. taken-10%"
        }
    }, 
    [5]={
        ["log_name"]="cichol's mantle", 
        ["count"]=1, 
        ["id"]=26246, 
        ["name"]="cichol's mantle", 
        ["augments"]={
            [1]="STR+20", 
            [2]="Accuracy+20 Attack+20", 
            [3]="STR+10", 
            [4]="Weapon skill damage +10%", 
            [5]="Phys. dmg. taken-10%"
        }
    }, 
    [6]={
        ["log_name"]="reiki cloak", 
        ["id"]=27615, 
        ["name"]="reiki cloak", 
        ["count"]=1
    }, 
    [7]={
        ["log_name"]="leyline gloves", 
        ["id"]=27135, 
        ["name"]="leyline gloves", 
        ["count"]=1
    }
}