-- Generated by the Organizer Library (Sun Nov 16 12:49:48 2025)
return {
    [1]={
        ["log_name"]="mafic cudgel", 
        ["id"]=21102, 
        ["name"]="mafic cudgel", 
        ["count"]=1
    }, 
    [2]={
        ["log_name"]="gozuki mezuki", 
        ["id"]=22056, 
        ["name"]="gozuki mezuki", 
        ["count"]=1
    }, 
    [3]={
        ["log_name"]="toreutic escutcheon", 
        ["id"]=26437, 
        ["name"]="tr. escutcheon", 
        ["count"]=1
    }, 
    [4]={
        ["log_name"]="kustawi +1", 
        ["id"]=20581, 
        ["name"]="kustawi +1", 
        ["count"]=1
    }, 
    [5]={
        ["log_name"]="tauret", 
        ["id"]=21565, 
        ["name"]="tauret", 
        ["count"]=1
    }
}