-- Generated by the Organizer Library (Sun Mar 16 01:01:59 2025)
return {
    [1]={
        ["log_name"]="goldsmith's smock", 
        ["id"]=11331, 
        ["name"]="goldsmith's smock", 
        ["count"]=1
    }, 
    [2]={
        ["log_name"]="crepuscular mail", 
        ["id"]=23798, 
        ["name"]="crepuscular mail", 
        ["count"]=1
    }, 
    [3]={
        ["log_name"]="thereoid greaves", 
        ["id"]=27503, 
        ["name"]="thereoid greaves", 
        ["count"]=1
    }, 
    [4]={
        ["log_name"]="souveran schaller +1", 
        ["count"]=1, 
        ["id"]=26671, 
        ["name"]="souv. schaller +1", 
        ["augments"]={
            [1]="HP+105", 
            [2]="Enmity+9", 
            [3]="Potency of \"Cure\" effect received +15%"
        }
    }, 
    [5]={
        ["log_name"]="aurgelmir orb +1", 
        ["id"]=22298, 
        ["name"]="aurgelmir orb +1", 
        ["count"]=1
    }, 
    [6]={
        ["log_name"]="engraved belt", 
        ["id"]=28414, 
        ["name"]="engraved belt", 
        ["count"]=1
    }, 
    [7]={
        ["log_name"]="tatenashi haidate +1", 
        ["count"]=1, 
        ["id"]=25856, 
        ["name"]="tatena. haidate +1", 
        ["augments"]={
            [1]="Path: A"
        }
    }, 
    [8]={
        ["log_name"]="moonlight ring", 
        ["id"]=26190, 
        ["name"]="moonlight ring", 
        ["count"]=1
    }, 
    [9]={
        ["log_name"]="passion jacket", 
        ["id"]=25727, 
        ["name"]="passion jacket", 
        ["count"]=1
    }
}