-- Generated by the Organizer Library (Sun Nov 16 12:49:48 2025)
return {
    [1]={
        ["log_name"]="nyame helm", 
        ["count"]=1, 
        ["id"]=23761, 
        ["name"]="nyame helm", 
        ["augments"]={
            [1]="Path: B"
        }
    }, 
    [2]={
        ["log_name"]="malignance chapeau", 
        ["id"]=23732, 
        ["name"]="malignance chapeau", 
        ["count"]=1
    }, 
    [3]={
        ["log_name"]="ishvara earring", 
        ["id"]=27537, 
        ["name"]="ishvara earring", 
        ["count"]=1
    }, 
    [4]={
        ["log_name"]="stikini ring +1", 
        ["id"]=26184, 
        ["name"]="stikini ring +1", 
        ["count"]=1
    }, 
    [5]={
        ["log_name"]="stikini ring +1", 
        ["id"]=26184, 
        ["name"]="stikini ring +1", 
        ["count"]=1
    }, 
    [6]={
        ["log_name"]="nyame mail", 
        ["count"]=1, 
        ["id"]=23768, 
        ["name"]="nyame mail", 
        ["augments"]={
            [1]="Path: B"
        }
    }, 
    [7]={
        ["log_name"]="orpheus's sash", 
        ["id"]=26359, 
        ["name"]="orpheus's sash", 
        ["count"]=1
    }, 
    [8]={
        ["log_name"]="fucho-no-obi", 
        ["id"]=28452, 
        ["name"]="fucho-no-obi", 
        ["count"]=1
    }, 
    [9]={
        ["log_name"]="eihwaz ring", 
        ["id"]=10798, 
        ["name"]="eihwaz ring", 
        ["count"]=1
    }, 
    [10]={
        ["log_name"]="moonbow belt +1", 
        ["id"]=26341, 
        ["name"]="moonbow belt +1", 
        ["count"]=1
    }, 
    [11]={
        ["log_name"]="herculean gloves", 
        ["count"]=1, 
        ["id"]=27140, 
        ["name"]="herculean gloves", 
        ["augments"]={
            [1]="Pet: \"Mag.Atk.Bns.\"+28", 
            [2]="Pet: \"Store TP\"+6", 
            [3]="Pet: DEX+1"
        }
    }, 
    [12]={
        ["log_name"]="eabani earring", 
        ["id"]=27540, 
        ["name"]="eabani earring", 
        ["count"]=1
    }, 
    [13]={
        ["log_name"]="ryuo somen +1", 
        ["count"]=1, 
        ["id"]=25612, 
        ["name"]="ryuo somen +1", 
        ["augments"]={
            [1]="HP+65", 
            [2]="\"Store TP\"+5", 
            [3]="\"Subtle Blow\"+8"
        }
    }, 
    [14]={
        ["log_name"]="pemphredo tathlum", 
        ["id"]=22271, 
        ["name"]="pemphredo tathlum", 
        ["count"]=1
    }, 
    [15]={
        ["log_name"]="nyame flanchard", 
        ["count"]=1, 
        ["id"]=23782, 
        ["name"]="nyame flanchard", 
        ["augments"]={
            [1]="Path: B"
        }
    }, 
    [16]={
        ["log_name"]="malignance boots", 
        ["id"]=23736, 
        ["name"]="malignance boots", 
        ["count"]=1
    }, 
    [17]={
        ["log_name"]="craftmaster's ring", 
        ["id"]=28586, 
        ["name"]="craftmaster's ring", 
        ["count"]=1
    }, 
    [18]={
        ["log_name"]="craftkeeper's ring", 
        ["id"]=28585, 
        ["name"]="craftkeeper's ring", 
        ["count"]=1
    }, 
    [19]={
        ["log_name"]="orvail ring +1", 
        ["id"]=26203, 
        ["name"]="orvail ring +1", 
        ["count"]=1
    }, 
    [20]={
        ["log_name"]="artificer's ring", 
        ["id"]=28587, 
        ["name"]="artificer's ring", 
        ["count"]=1
    }, 
    [21]={
        ["log_name"]="telos earring", 
        ["id"]=27545, 
        ["name"]="telos earring", 
        ["count"]=1
    }, 
    [22]={
        ["log_name"]="nyame gauntlets", 
        ["count"]=1, 
        ["id"]=23775, 
        ["name"]="nyame gauntlets", 
        ["augments"]={
            [1]="Path: B"
        }
    }, 
    [23]={
        ["log_name"]="suit of adamantite armor", 
        ["id"]=23861, 
        ["name"]="adamantite armor", 
        ["count"]=1
    }, 
    [24]={
        ["log_name"]="friomisi earring", 
        ["id"]=28514, 
        ["name"]="friomisi earring", 
        ["count"]=1
    }, 
    [25]={
        ["log_name"]="nyame sollerets", 
        ["count"]=1, 
        ["id"]=23789, 
        ["name"]="nyame sollerets", 
        ["augments"]={
            [1]="Path: B"
        }
    }, 
    [26]={
        ["log_name"]="hecate's earring", 
        ["id"]=11698, 
        ["name"]="hecate's earring", 
        ["count"]=1
    }, 
    [27]={
        ["log_name"]="moonshade earring", 
        ["count"]=1, 
        ["id"]=11697, 
        ["name"]="moonshade earring", 
        ["augments"]={
            [1]="Accuracy+4", 
            [2]="TP Bonus +250"
        }
    }, 
    [28]={
        ["log_name"]="andoaa earring", 
        ["id"]=28506, 
        ["name"]="andoaa earring", 
        ["count"]=1
    }, 
    [29]={
        ["log_name"]="malignance gloves", 
        ["id"]=23734, 
        ["name"]="malignance gloves", 
        ["count"]=1
    }, 
    [30]={
        ["log_name"]="cryptic earring", 
        ["id"]=28483, 
        ["name"]="cryptic earring", 
        ["count"]=1
    }
}