-- Generated by the Organizer Library (Sun Nov 16 12:49:48 2025)
return {
    [1]={
        ["log_name"]="taeon tabard", 
        ["count"]=1, 
        ["id"]=26893, 
        ["name"]="taeon tabard", 
        ["augments"]={
            [1]="Pet: Attack+25 Pet: Rng.Atk.+25", 
            [2]="Pet: \"Dbl. Atk.\"+5", 
            [3]="Pet: Damage taken -4%"
        }
    }, 
    [2]={
        ["log_name"]="herculean boots", 
        ["count"]=1, 
        ["id"]=27496, 
        ["name"]="herculean boots", 
        ["augments"]={
            [1]="Attack+5", 
            [2]="\"Triple Atk.\"+4", 
            [3]="AGI+4", 
            [4]="Accuracy+1"
        }
    }, 
    [3]={
        ["log_name"]="goldsmith's smock", 
        ["id"]=11331, 
        ["name"]="goldsmith's smock", 
        ["count"]=1
    }, 
    [4]={
        ["log_name"]="sroda earring", 
        ["id"]=26118, 
        ["name"]="sroda earring", 
        ["count"]=1
    }, 
    [5]={
        ["log_name"]="crematio earring", 
        ["id"]=28517, 
        ["name"]="crematio earring", 
        ["count"]=1
    }, 
    [6]={
        ["log_name"]="skrymir cord", 
        ["id"]=26356, 
        ["name"]="skrymir cord", 
        ["count"]=1
    }, 
    [7]={
        ["log_name"]="rao kote +1", 
        ["count"]=1, 
        ["id"]=27027, 
        ["name"]="rao kote +1", 
        ["augments"]={
            [1]="Pet: HP+125", 
            [2]="Pet: Accuracy+20", 
            [3]="Pet: Damage taken -4%"
        }
    }, 
    [8]={
        ["log_name"]="malignance tabard", 
        ["id"]=23733, 
        ["name"]="malignance tabard", 
        ["count"]=1
    }, 
    [9]={
        ["log_name"]="rao togi +1", 
        ["count"]=1, 
        ["id"]=26851, 
        ["name"]="rao togi +1", 
        ["augments"]={
            [1]="Pet: HP+125", 
            [2]="Pet: Accuracy+20", 
            [3]="Pet: Damage taken -4%"
        }
    }, 
    [10]={
        ["log_name"]="passion jacket", 
        ["id"]=25727, 
        ["name"]="passion jacket", 
        ["count"]=1
    }, 
    [11]={
        ["log_name"]="heyoka cap +1", 
        ["id"]=25564, 
        ["name"]="heyoka cap +1", 
        ["count"]=1
    }, 
    [12]={
        ["log_name"]="orunmila's torque", 
        ["id"]=10394, 
        ["name"]="orunmila's torque", 
        ["count"]=1
    }, 
    [13]={
        ["log_name"]="taeon chapeau", 
        ["count"]=1, 
        ["id"]=26735, 
        ["name"]="taeon chapeau", 
        ["augments"]={
            [1]="Pet: Attack+25 Pet: Rng.Atk.+25", 
            [2]="Pet: \"Dbl. Atk.\"+5", 
            [3]="Pet: Damage taken -4%"
        }
    }, 
    [14]={
        ["log_name"]="doyen pants", 
        ["id"]=27289, 
        ["name"]="doyen pants", 
        ["count"]=1
    }, 
    [15]={
        ["log_name"]="heyoka subligar +1", 
        ["id"]=25904, 
        ["name"]="heyoka subligar +1", 
        ["count"]=1
    }, 
    [16]={
        ["log_name"]="malignance tights", 
        ["id"]=23735, 
        ["name"]="malignance tights", 
        ["count"]=1
    }, 
    [17]={
        ["log_name"]="rao kabuto +1", 
        ["count"]=1, 
        ["id"]=26675, 
        ["name"]="rao kabuto +1", 
        ["augments"]={
            [1]="Pet: HP+125", 
            [2]="Pet: Accuracy+20", 
            [3]="Pet: Damage taken -4%"
        }
    }, 
    [18]={
        ["log_name"]="taeon gloves", 
        ["count"]=1, 
        ["id"]=27047, 
        ["name"]="taeon gloves", 
        ["augments"]={
            [1]="Pet: Attack+23 Pet: Rng.Atk.+23", 
            [2]="Pet: \"Dbl. Atk.\"+5", 
            [3]="Pet: Damage taken -4%"
        }
    }, 
    [19]={
        ["log_name"]="goldsmith's torque", 
        ["id"]=10950, 
        ["name"]="goldsm. torque", 
        ["count"]=1
    }, 
    [20]={
        ["log_name"]="herculean helm", 
        ["count"]=1, 
        ["id"]=25642, 
        ["name"]="herculean helm", 
        ["augments"]={
            [1]="Pet: Accuracy+9 Pet: Rng. Acc.+9", 
            [2]="Pet: \"Store TP\"+11", 
            [3]="Pet: CHR+2", 
            [4]="Pet: \"Mag.Atk.Bns.\"+8"
        }
    }, 
    [21]={
        ["log_name"]="udug jacket", 
        ["id"]=25788, 
        ["name"]="udug jacket", 
        ["count"]=1
    }, 
    [22]={
        ["log_name"]="annointed kalasiris", 
        ["id"]=26960, 
        ["name"]="annoint. kalasiris", 
        ["count"]=1
    }
}