-- Generated by the Organizer Library (Sun Mar 16 01:01:59 2025)
return {
    [1]={
        ["log_name"]="perfect lucky egg", 
        ["id"]=22299, 
        ["name"]="per. lucky egg", 
        ["count"]=1
    }, 
    [2]={
        ["log_name"]="prolix ring", 
        ["id"]=10752, 
        ["name"]="prolix ring", 
        ["count"]=1
    }, 
    [3]={
        ["log_name"]="trollbane", 
        ["id"]=18694, 
        ["name"]="trollbane", 
        ["count"]=1
    }, 
    [4]={
        ["log_name"]="eluder's sachet", 
        ["id"]=19781, 
        ["name"]="eluder's sachet", 
        ["count"]=1
    }, 
    [5]={
        ["log_name"]="odnowa earring +1", 
        ["count"]=1, 
        ["id"]=27549, 
        ["name"]="odnowa earring +1", 
        ["augments"]={
            [1]="Path: A"
        }
    }, 
    [6]={
        ["log_name"]="white rarab cap +1", 
        ["id"]=25679, 
        ["name"]="wh. rarab cap +1", 
        ["count"]=1
    }, 
    [7]={
        ["log_name"]="kyrene's earring", 
        ["id"]=26078, 
        ["name"]="kyrene's earring", 
        ["count"]=1
    }, 
    [8]={
        ["log_name"]="shabti cuisses +1", 
        ["id"]=28179, 
        ["name"]="shabti cuisses +1", 
        ["count"]=1
    }, 
    [9]={
        ["log_name"]="infused earring", 
        ["id"]=28475, 
        ["name"]="infused earring", 
        ["count"]=1
    }, 
    [10]={
        ["log_name"]="warder's charm +1", 
        ["count"]=1, 
        ["id"]=27505, 
        ["name"]="warder's charm +1", 
        ["augments"]={
            [1]="Path: A"
        }
    }, 
    [11]={
        ["log_name"]="suppanomimi", 
        ["id"]=14739, 
        ["name"]="suppanomimi", 
        ["count"]=1
    }, 
    [12]={
        ["log_name"]="chirich ring +1", 
        ["id"]=26182, 
        ["name"]="chirich ring +1", 
        ["count"]=1
    }, 
    [13]={
        ["log_name"]="chirich ring +1", 
        ["id"]=26182, 
        ["name"]="chirich ring +1", 
        ["count"]=1
    }, 
    [14]={
        ["log_name"]="yetshila +1", 
        ["id"]=21379, 
        ["name"]="yetshila +1", 
        ["count"]=1
    }, 
    [15]={
        ["log_name"]="tuisto earring", 
        ["id"]=26112, 
        ["name"]="tuisto earring", 
        ["count"]=1
    }, 
    [16]={
        ["log_name"]="gelatinous ring +1", 
        ["count"]=1, 
        ["id"]=10769, 
        ["name"]="gelatinous ring +1", 
        ["augments"]={
            [1]="Path: A"
        }
    }, 
    [17]={
        ["log_name"]="vim torque +1", 
        ["id"]=26022, 
        ["name"]="vim torque +1", 
        ["count"]=1
    }, 
    [18]={
        ["log_name"]="caduceus", 
        ["id"]=17058, 
        ["name"]="caduceus", 
        ["count"]=1
    }, 
    [19]={
        ["log_name"]="unmoving collar +1", 
        ["count"]=1, 
        ["id"]=27509, 
        ["name"]="unmoving collar +1", 
        ["augments"]={
            [1]="Path: A"
        }
    }, 
    [20]={
        ["log_name"]="platinum moogle belt", 
        ["id"]=26366, 
        ["name"]="plat. mog. belt", 
        ["count"]=1
    }, 
    [21]={
        ["id"]=17040, 
        ["name"]="warp cudgel", 
        ["count"]=1, 
        ["log_name"]="warp cudgel"
    }
}