-- Generated by the Organizer Library (Sun Nov 16 12:49:48 2025)
return {
    [1]={
        ["log_name"]="herculean boots", 
        ["count"]=1, 
        ["id"]=27496, 
        ["name"]="herculean boots", 
        ["augments"]={
            [1]="Pet: Accuracy+12 Pet: Rng. Acc.+12", 
            [2]="Pet: \"Store TP\"+11", 
            [3]="Pet: MND+2", 
            [4]="Pet: \"Mag.Atk.Bns.\"+13"
        }
    }, 
    [2]={
        ["log_name"]="regal pumps +1", 
        ["count"]=1, 
        ["id"]=28274, 
        ["name"]="regal pumps +1", 
        ["augments"]={
            [1]="Path: A"
        }
    }, 
    [3]={
        ["log_name"]="epona's ring", 
        ["id"]=11651, 
        ["name"]="epona's ring", 
        ["count"]=1
    }, 
    [4]={
        ["log_name"]="mpaca's doublet", 
        ["id"]=23765, 
        ["name"]="mpaca's doublet", 
        ["count"]=1
    }, 
    [5]={
        ["log_name"]="eluder's sachet", 
        ["id"]=19781, 
        ["name"]="eluder's sachet", 
        ["count"]=1
    }, 
    [6]={
        ["log_name"]="cohort cloak +1", 
        ["count"]=1, 
        ["id"]=25681, 
        ["name"]="cohort cloak +1", 
        ["augments"]={
            [1]="Path: A"
        }
    }, 
    [7]={
        ["log_name"]="midnights", 
        ["count"]=1, 
        ["id"]=20520, 
        ["name"]="midnights", 
        ["augments"]={
            [1]="Pet: Attack+25", 
            [2]="Pet: Accuracy+25", 
            [3]="Pet: Damage taken -3%"
        }
    }, 
    [8]={
        ["log_name"]="pratik earring", 
        ["id"]=28498, 
        ["name"]="pratik earring", 
        ["count"]=1
    }, 
    [9]={
        ["log_name"]="ukko sash", 
        ["id"]=28432, 
        ["name"]="ukko sash", 
        ["count"]=1
    }, 
    [10]={
        ["log_name"]="sherida earring", 
        ["id"]=26084, 
        ["name"]="sherida earring", 
        ["count"]=1
    }, 
    [11]={
        ["log_name"]="klouskap sash +1", 
        ["id"]=26336, 
        ["name"]="klouskap sash +1", 
        ["count"]=1
    }, 
    [12]={
        ["log_name"]="mpaca's cap", 
        ["count"]=1, 
        ["id"]=23758, 
        ["name"]="mpaca's cap", 
        ["augments"]={
            [1]="Path: A"
        }
    }, 
    [13]={
        ["log_name"]="kyrene's earring", 
        ["id"]=26078, 
        ["name"]="kyrene's earring", 
        ["count"]=1
    }, 
    [14]={
        ["log_name"]="herculean gloves", 
        ["count"]=1, 
        ["id"]=27140, 
        ["name"]="herculean gloves", 
        ["augments"]={
            [1]="Pet: Mag. Acc.+25", 
            [2]="Pet: \"Store TP\"+11", 
            [3]="Pet: VIT+9", 
            [4]="Pet: Attack+14 Pet: Rng.Atk.+14", 
            [5]="Pet: \"Mag.Atk.Bns.\"+5"
        }
    }, 
    [15]={
        ["log_name"]="godhands", 
        ["id"]=20515, 
        ["name"]="godhands", 
        ["count"]=1
    }, 
    [16]={
        ["log_name"]="odnowa earring +1", 
        ["count"]=1, 
        ["id"]=27549, 
        ["name"]="odnowa earring +1", 
        ["augments"]={
            [1]="Path: A"
        }
    }, 
    [17]={
        ["log_name"]="xiucoatl", 
        ["count"]=1, 
        ["id"]=21526, 
        ["name"]="xiucoatl", 
        ["augments"]={
            [1]="Path: C"
        }
    }, 
    [18]={
        ["log_name"]="mpaca's hose", 
        ["count"]=1, 
        ["id"]=23779, 
        ["name"]="mpaca's hose", 
        ["augments"]={
            [1]="Path: A"
        }
    }, 
    [19]={
        ["log_name"]="prolix ring", 
        ["id"]=10752, 
        ["name"]="prolix ring", 
        ["count"]=1
    }, 
    [20]={
        ["log_name"]="infused earring", 
        ["id"]=28475, 
        ["name"]="infused earring", 
        ["count"]=1
    }, 
    [21]={
        ["log_name"]="warder's charm +1", 
        ["count"]=1, 
        ["id"]=27505, 
        ["name"]="warder's charm +1", 
        ["augments"]={
            [1]="Path: A"
        }
    }, 
    [22]={
        ["log_name"]="chirich ring +1", 
        ["id"]=26182, 
        ["name"]="chirich ring +1", 
        ["count"]=1
    }, 
    [23]={
        ["log_name"]="chirich ring +1", 
        ["id"]=26182, 
        ["name"]="chirich ring +1", 
        ["count"]=1
    }, 
    [24]={
        ["log_name"]="ohtas", 
        ["id"]=20535, 
        ["name"]="ohtas", 
        ["count"]=1
    }, 
    [25]={
        ["log_name"]="empath necklace", 
        ["id"]=27514, 
        ["name"]="empath necklace", 
        ["count"]=1
    }, 
    [26]={
        ["log_name"]="niobid strap", 
        ["id"]=22197, 
        ["name"]="niobid strap", 
        ["count"]=1
    }, 
    [27]={
        ["log_name"]="mpaca's boots", 
        ["id"]=23786, 
        ["name"]="mpaca's boots", 
        ["count"]=1
    }, 
    [28]={
        ["log_name"]="taeon tights", 
        ["count"]=1, 
        ["id"]=27234, 
        ["name"]="taeon tights", 
        ["augments"]={
            [1]="Pet: Attack+22 Pet: Rng.Atk.+22", 
            [2]="Pet: \"Dbl. Atk.\"+5", 
            [3]="Pet: Damage taken -4%"
        }
    }, 
    [29]={
        ["log_name"]="volte mittens", 
        ["id"]=23719, 
        ["name"]="volte mittens", 
        ["count"]=1
    }, 
    [30]={
        ["log_name"]="tuisto earring", 
        ["id"]=26112, 
        ["name"]="tuisto earring", 
        ["count"]=1
    }, 
    [31]={
        ["log_name"]="mpaca's gloves", 
        ["id"]=23772, 
        ["name"]="mpaca's gloves", 
        ["count"]=1
    }, 
    [32]={
        ["log_name"]="gelatinous ring +1", 
        ["count"]=1, 
        ["id"]=10769, 
        ["name"]="gelatinous ring +1", 
        ["augments"]={
            [1]="Path: A"
        }
    }, 
    [33]={
        ["log_name"]="enmerkar earring", 
        ["id"]=26083, 
        ["name"]="enmerkar earring", 
        ["count"]=1
    }, 
    [34]={
        ["log_name"]="incarnation sash", 
        ["id"]=28418, 
        ["name"]="incarnation sash", 
        ["count"]=1
    }, 
    [35]={
        ["log_name"]="isa belt", 
        ["id"]=28451, 
        ["name"]="isa belt", 
        ["count"]=1
    }, 
    [36]={
        ["log_name"]="unmoving collar +1", 
        ["count"]=1, 
        ["id"]=27509, 
        ["name"]="unmoving collar +1", 
        ["augments"]={
            [1]="Path: A"
        }
    }, 
    [37]={
        ["log_name"]="domesticator's earring", 
        ["id"]=28505, 
        ["name"]="domes. earring", 
        ["count"]=1
    }, 
    [38]={
        ["log_name"]="condemners", 
        ["id"]=20505, 
        ["name"]="condemners", 
        ["count"]=1
    }
}