-- Generated by the Organizer Library (Sun Mar 16 01:01:59 2025)
return {
    [1]={
        ["log_name"]="throwing tomahawk", 
        ["id"]=18258, 
        ["name"]="thr. tomahawk", 
        ["count"]=1
    }, 
    [2]={
        ["log_name"]="boii cuisses +3", 
        ["id"]=23621, 
        ["name"]="boii cuisses +3", 
        ["count"]=1
    }, 
    [3]={
        ["log_name"]="agoge mufflers +3", 
        ["id"]=23532, 
        ["name"]="agoge mufflers +3", 
        ["count"]=1
    }, 
    [4]={
        ["log_name"]="agoge mask +3", 
        ["count"]=1, 
        ["id"]=23398, 
        ["name"]="agoge mask +3", 
        ["augments"]={
            [1]="Enhances \"Savagery\" effect"
        }
    }, 
    [5]={
        ["log_name"]="boii lorica +3", 
        ["id"]=23487, 
        ["name"]="boii lorica +3", 
        ["count"]=1
    }, 
    [6]={
        ["log_name"]="profane staff", 
        ["id"]=22071, 
        ["name"]="profane staff", 
        ["count"]=1
    }, 
    [7]={
        ["log_name"]="flamma manopolas +2", 
        ["id"]=25835, 
        ["name"]="flam. manopolas +2", 
        ["count"]=1
    }, 
    [8]={
        ["log_name"]="begrudging ring", 
        ["id"]=26172, 
        ["name"]="begrudging ring", 
        ["count"]=1
    }, 
    [9]={
        ["log_name"]="boii mufflers +3", 
        ["id"]=23554, 
        ["name"]="boii mufflers +3", 
        ["count"]=1
    }, 
    [10]={
        ["log_name"]="agoge cuisses +3", 
        ["id"]=23599, 
        ["name"]="agoge cuisses +3", 
        ["count"]=1
    }, 
    [11]={
        ["log_name"]="pummeler's cuisses +3", 
        ["id"]=23576, 
        ["name"]="pumm. cuisses +3", 
        ["count"]=1
    }, 
    [12]={
        ["log_name"]="eschan stone", 
        ["id"]=28415, 
        ["name"]="eschan stone", 
        ["count"]=1
    }, 
    [13]={
        ["log_name"]="agoge calligae +3", 
        ["id"]=23666, 
        ["name"]="agoge calligae +3", 
        ["count"]=1
    }, 
    [14]={
        ["log_name"]="boii earring +1", 
        ["id"]=25421, 
        ["name"]="boii earring +1", 
        ["count"]=1
    }, 
    [15]={
        ["log_name"]="pummeler's calligae +3", 
        ["id"]=23643, 
        ["name"]="pumm. calligae +3", 
        ["count"]=1
    }, 
    [16]={
        ["log_name"]="agoge lorica +3", 
        ["id"]=23465, 
        ["name"]="agoge lorica +3", 
        ["count"]=1
    }, 
    [17]={
        ["log_name"]="shabti sabatons", 
        ["id"]=28316, 
        ["name"]="shabti sabatons", 
        ["count"]=1
    }, 
    [18]={
        ["log_name"]="boii calligae +2", 
        ["id"]=23353, 
        ["name"]="boii calligae +2", 
        ["count"]=1
    }, 
    [19]={
        ["log_name"]="qutrub knife", 
        ["id"]=20576, 
        ["name"]="qutrub knife", 
        ["count"]=1
    }, 
    [20]={
        ["log_name"]="volte sollerets", 
        ["id"]=23728, 
        ["name"]="volte sollerets", 
        ["count"]=1
    }, 
    [21]={
        ["log_name"]="pummeler's lorica +3", 
        ["id"]=23442, 
        ["name"]="pumm. lorica +3", 
        ["count"]=1
    }, 
    [22]={
        ["log_name"]="boii mask +2", 
        ["id"]=23085, 
        ["name"]="boii mask +2", 
        ["count"]=1
    }, 
    [23]={
        ["id"]=6343, 
        ["name"]="grape daifuku", 
        ["count"]=12, 
        ["log_name"]="grape daifuku"
    }, 
    [24]={
        ["id"]=9149, 
        ["name"]="hidhaegg's scale", 
        ["count"]=12, 
        ["log_name"]="hidhaegg's scale"
    }, 
    [25]={
        ["id"]=4165, 
        ["name"]="silent oil", 
        ["count"]=12, 
        ["log_name"]="pot of silent oil"
    }, 
    [26]={
        ["id"]=6462, 
        ["name"]="salt ramen", 
        ["count"]=12, 
        ["log_name"]="bowl of salt ramen"
    }, 
    [27]={
        ["id"]=6608, 
        ["name"]="moogle amp.", 
        ["count"]=99, 
        ["log_name"]="moogle amplifier"
    }, 
    [28]={
        ["id"]=4174, 
        ["name"]="vile elixir", 
        ["count"]=1, 
        ["log_name"]="vile elixir"
    }, 
    [29]={
        ["id"]=4172, 
        ["name"]="reraiser", 
        ["count"]=1, 
        ["log_name"]="reraiser"
    }, 
    [30]={
        ["id"]=4154, 
        ["name"]="holy water", 
        ["count"]=12, 
        ["log_name"]="flask of holy water"
    }, 
    [31]={
        ["id"]=4155, 
        ["name"]="remedy", 
        ["count"]=12, 
        ["log_name"]="remedy"
    }, 
    [32]={
        ["id"]=9151, 
        ["name"]="sovereign's hide", 
        ["count"]=12, 
        ["log_name"]="sovereign behemoth's hide"
    }, 
    [33]={
        ["id"]=9203, 
        ["name"]="tumult's blood", 
        ["count"]=12, 
        ["log_name"]="vial of the tumult curator's blood"
    }, 
    [34]={
        ["id"]=6339, 
        ["name"]="rolan. daifuku", 
        ["count"]=12, 
        ["log_name"]="rolanberry daifuku"
    }, 
    [35]={
        ["id"]=5759, 
        ["name"]="red curry bun", 
        ["count"]=12, 
        ["log_name"]="red curry bun"
    }, 
    [36]={
        ["id"]=25679, 
        ["name"]="wh. rarab cap +1", 
        ["count"]=1, 
        ["log_name"]="white rarab cap +1"
    }, 
    [37]={
        ["id"]=4153, 
        ["name"]="antacid", 
        ["count"]=12, 
        ["log_name"]="bottle of antacid"
    }, 
    [38]={
        ["id"]=6274, 
        ["name"]="pukatrice egg", 
        ["count"]=12, 
        ["log_name"]="pukatrice egg"
    }, 
    [39]={
        ["id"]=6601, 
        ["name"]="om. sandwich", 
        ["count"]=12, 
        ["log_name"]="omelette sandwich"
    }, 
    [40]={
        ["id"]=4149, 
        ["name"]="panacea", 
        ["count"]=12, 
        ["log_name"]="flask of panacea"
    }, 
    [41]={
        ["id"]=4175, 
        ["name"]="vile elixir +1", 
        ["count"]=1, 
        ["log_name"]="vile elixir +1"
    }, 
    [42]={
        ["id"]=4173, 
        ["name"]="hi-reraiser", 
        ["count"]=1, 
        ["log_name"]="hi-reraiser"
    }, 
    [43]={
        ["id"]=9205, 
        ["name"]="sarama's hide", 
        ["count"]=12, 
        ["log_name"]="sarama's hide"
    }, 
    [44]={
        ["id"]=1179, 
        ["name"]="shihei", 
        ["count"]=99, 
        ["log_name"]="shihei"
    }, 
    [45]={
        ["id"]=4164, 
        ["name"]="prism powder", 
        ["count"]=12, 
        ["log_name"]="pinch of prism powder"
    }, 
    [46]={
        ["id"]=4213, 
        ["name"]="icarus wing", 
        ["count"]=12, 
        ["log_name"]="icarus wing"
    }
}