-- Generated by the Organizer Library (Sun Nov 16 12:49:48 2025)
return {
    [1]={
        ["log_name"]="sibyl scarf", 
        ["id"]=25416, 
        ["name"]="sibyl scarf", 
        ["count"]=1
    }, 
    [2]={
        ["log_name"]="can of automaton oil +3", 
        ["id"]=19185, 
        ["name"]="automat. oil +3", 
        ["count"]=1
    }, 
    [3]={
        ["log_name"]="perfect lucky egg", 
        ["id"]=22299, 
        ["name"]="per. lucky egg", 
        ["count"]=1
    }, 
    [4]={
        ["log_name"]="karagoz cappello +2", 
        ["id"]=23102, 
        ["name"]="kara. cappello +2", 
        ["count"]=1
    }, 
    [5]={
        ["log_name"]="karagoz farsetto +2", 
        ["id"]=23169, 
        ["name"]="kara. farsetto +2", 
        ["count"]=1
    }, 
    [6]={
        ["log_name"]="tali'ah turban +2", 
        ["id"]=25573, 
        ["name"]="tali'ah turban +2", 
        ["count"]=1
    }, 
    [7]={
        ["log_name"]="karagoz pantaloni +2", 
        ["id"]=23303, 
        ["name"]="kara. pantaloni +2", 
        ["count"]=1
    }, 
    [8]={
        ["log_name"]="guignol earring", 
        ["id"]=15999, 
        ["name"]="guignol earring", 
        ["count"]=1
    }, 
    [9]={
        ["log_name"]="pitre tobe +3", 
        ["count"]=1, 
        ["id"]=23482, 
        ["name"]="pitre tobe +3", 
        ["augments"]={
            [1]="Enhances \"Overdrive\" effect"
        }
    }, 
    [10]={
        ["log_name"]="denouements", 
        ["id"]=20516, 
        ["name"]="denouements", 
        ["count"]=1
    }, 
    [11]={
        ["log_name"]="karagoz guanti +2", 
        ["id"]=23236, 
        ["name"]="karagoz guanti +2", 
        ["count"]=1
    }, 
    [12]={
        ["log_name"]="pitre taj +3", 
        ["count"]=1, 
        ["id"]=23415, 
        ["name"]="pitre taj +3", 
        ["augments"]={
            [1]="Enhances \"Optimization\" effect"
        }
    }, 
    [13]={
        ["log_name"]="karagoz scarpe +2", 
        ["id"]=23370, 
        ["name"]="karagoz scarpe +2", 
        ["count"]=1
    }, 
    [14]={
        ["log_name"]="pitre babouches +3", 
        ["count"]=1, 
        ["id"]=23683, 
        ["name"]="pitre babouches +3", 
        ["augments"]={
            [1]="Enhances \"Role Reversal\" effect"
        }
    }, 
    [15]={
        ["log_name"]="taeon chapeau", 
        ["count"]=1, 
        ["id"]=26735, 
        ["name"]="taeon chapeau", 
        ["augments"]={
            [1]="Phalanx +3"
        }
    }, 
    [16]={
        ["log_name"]="heyoka mittens", 
        ["id"]=25990, 
        ["name"]="heyoka mittens", 
        ["count"]=1
    }, 
    [17]={
        ["log_name"]="tali'ah crackows +2", 
        ["id"]=25952, 
        ["name"]="tali'ah crackows +2", 
        ["count"]=1
    }, 
    [18]={
        ["log_name"]="foire babouches +3", 
        ["id"]=23660, 
        ["name"]="foire babouches +3", 
        ["count"]=1
    }, 
    [19]={
        ["log_name"]="mache earring +1", 
        ["id"]=26081, 
        ["name"]="mache earring +1", 
        ["count"]=1
    }, 
    [20]={
        ["log_name"]="foire dastanas +3", 
        ["id"]=23526, 
        ["name"]="foire dastanas +3", 
        ["count"]=1
    }, 
    [21]={
        ["log_name"]="pitre churidars +3", 
        ["count"]=1, 
        ["id"]=23616, 
        ["name"]="pitre churidars +3", 
        ["augments"]={
            [1]="Enhances \"Ventriloquy\" effect"
        }
    }, 
    [22]={
        ["log_name"]="republican platinum medal", 
        ["id"]=25415, 
        ["name"]="rep. plat. medal", 
        ["count"]=1
    }, 
    [23]={
        ["log_name"]="heyoka harness", 
        ["id"]=26539, 
        ["name"]="heyoka harness", 
        ["count"]=1
    }, 
    [24]={
        ["log_name"]="volte cap", 
        ["id"]=23713, 
        ["name"]="volte cap", 
        ["count"]=1
    }, 
    [25]={
        ["log_name"]="gelai earring", 
        ["id"]=28518, 
        ["name"]="gelai earring", 
        ["count"]=1
    }, 
    [26]={
        ["log_name"]="herculean helm", 
        ["count"]=1, 
        ["id"]=25642, 
        ["name"]="herculean helm", 
        ["augments"]={
            [1]="Pet: \"Mag.Atk.Bns.\"+26", 
            [2]="Pet: \"Dbl.Atk.\"+2 Pet: Crit.hit rate +2"
        }
    }, 
    [27]={
        ["log_name"]="tali'ah ring", 
        ["id"]=26210, 
        ["name"]="tali'ah ring", 
        ["count"]=1
    }, 
    [28]={
        ["log_name"]="platinum moogle belt", 
        ["id"]=26366, 
        ["name"]="plat. mog. belt", 
        ["count"]=1
    }, 
    [29]={
        ["log_name"]="volte spats", 
        ["id"]=23727, 
        ["name"]="volte spats", 
        ["count"]=1
    }, 
    [30]={
        ["log_name"]="goldsmith's belt", 
        ["id"]=15446, 
        ["name"]="goldsmith's belt", 
        ["count"]=1
    }, 
    [31]={
        ["log_name"]="hizamaru haramaki +2", 
        ["id"]=25792, 
        ["name"]="hiza. haramaki +2", 
        ["count"]=1
    }, 
    [32]={
        ["id"]=4165, 
        ["name"]="silent oil", 
        ["count"]=12, 
        ["log_name"]="pot of silent oil"
    }, 
    [33]={
        ["id"]=6343, 
        ["name"]="grape daifuku", 
        ["count"]=12, 
        ["log_name"]="grape daifuku"
    }, 
    [34]={
        ["id"]=21527, 
        ["name"]="sakpata's fists", 
        ["count"]=1, 
        ["log_name"]="sakpata's fists"
    }, 
    [35]={
        ["id"]=5759, 
        ["name"]="red curry bun", 
        ["count"]=12, 
        ["log_name"]="red curry bun"
    }, 
    [36]={
        ["id"]=21532, 
        ["name"]="varga purnikawa", 
        ["count"]=1, 
        ["log_name"]="varga purnikawa"
    }, 
    [37]={
        ["id"]=4153, 
        ["name"]="antacid", 
        ["count"]=12, 
        ["log_name"]="bottle of antacid"
    }, 
    [38]={
        ["id"]=6341, 
        ["name"]="bean daifuku", 
        ["count"]=12, 
        ["log_name"]="bean daifuku"
    }, 
    [39]={
        ["id"]=4175, 
        ["name"]="vile elixir +1", 
        ["count"]=1, 
        ["log_name"]="vile elixir +1"
    }, 
    [40]={
        ["id"]=4172, 
        ["name"]="reraiser", 
        ["count"]=1, 
        ["log_name"]="reraiser"
    }, 
    [41]={
        ["id"]=4154, 
        ["name"]="holy water", 
        ["count"]=12, 
        ["log_name"]="flask of holy water"
    }, 
    [42]={
        ["id"]=4155, 
        ["name"]="remedy", 
        ["count"]=12, 
        ["log_name"]="remedy"
    }, 
    [43]={
        ["id"]=4164, 
        ["name"]="prism powder", 
        ["count"]=12, 
        ["log_name"]="pinch of prism powder"
    }, 
    [44]={
        ["id"]=4213, 
        ["name"]="icarus wing", 
        ["count"]=12, 
        ["log_name"]="icarus wing"
    }
}