-- Generated by the Organizer Library (Sun Nov 16 12:49:48 2025)
return {
    [1]={
        ["log_name"]="herculean boots", 
        ["count"]=1, 
        ["id"]=27496, 
        ["name"]="herculean boots", 
        ["augments"]={
            [1]="Accuracy+8", 
            [2]="Pet: Attack+28 Pet: Rng.Atk.+28", 
            [3]="Phalanx +4", 
            [4]="Mag. Acc.+12 \"Mag.Atk.Bns.\"+12"
        }
    }, 
    [2]={
        ["log_name"]="crepuscular earring", 
        ["id"]=26117, 
        ["name"]="crep. earring", 
        ["count"]=1
    }, 
    [3]={
        ["log_name"]="fotia belt", 
        ["id"]=28420, 
        ["name"]="fotia belt", 
        ["count"]=1
    }, 
    [4]={
        ["log_name"]="shadow ring", 
        ["id"]=14646, 
        ["name"]="shadow ring", 
        ["count"]=1
    }, 
    [5]={
        ["log_name"]="shaded spectacles", 
        ["id"]=13945, 
        ["name"]="shaded specs.", 
        ["count"]=1
    }, 
    [6]={
        ["log_name"]="schere earring", 
        ["id"]=26116, 
        ["name"]="schere earring", 
        ["count"]=1
    }, 
    [7]={
        ["log_name"]="odnowa earring", 
        ["id"]=27548, 
        ["name"]="odnowa earring", 
        ["count"]=1
    }, 
    [8]={
        ["log_name"]="incanter's torque", 
        ["id"]=26016, 
        ["name"]="incanter's torque", 
        ["count"]=1
    }, 
    [9]={
        ["log_name"]="niqmaddu ring", 
        ["id"]=26185, 
        ["name"]="niqmaddu ring", 
        ["count"]=1
    }, 
    [10]={
        ["log_name"]="dignitary's earring", 
        ["id"]=27547, 
        ["name"]="digni. earring", 
        ["count"]=1
    }, 
    [11]={
        ["log_name"]="olympus sash", 
        ["id"]=10821, 
        ["name"]="olympus sash", 
        ["count"]=1
    }, 
    [12]={
        ["log_name"]="brutal earring", 
        ["id"]=14813, 
        ["name"]="brutal earring", 
        ["count"]=1
    }, 
    [13]={
        ["log_name"]="reti pendant", 
        ["id"]=27521, 
        ["name"]="reti pendant", 
        ["count"]=1
    }, 
    [14]={
        ["log_name"]="trux earring", 
        ["id"]=28515, 
        ["name"]="trux earring", 
        ["count"]=1
    }, 
    [15]={
        ["log_name"]="mephitas's ring +1", 
        ["count"]=1, 
        ["id"]=27559, 
        ["name"]="mephitas's ring +1", 
        ["augments"]={
            [1]="Path: A"
        }
    }, 
    [16]={
        ["log_name"]="herculean gloves", 
        ["count"]=1, 
        ["id"]=27140, 
        ["name"]="herculean gloves", 
        ["augments"]={
            [1]="Accuracy+11", 
            [2]="Pet: Phys. dmg. taken -5%", 
            [3]="Phalanx +4"
        }
    }, 
    [17]={
        ["log_name"]="haven hose", 
        ["id"]=11949, 
        ["name"]="haven hose", 
        ["count"]=1
    }, 
    [18]={
        ["log_name"]="regal ring", 
        ["id"]=26191, 
        ["name"]="regal ring", 
        ["count"]=1
    }, 
    [19]={
        ["log_name"]="cornelia's ring", 
        ["id"]=26227, 
        ["name"]="cornelia's ring", 
        ["count"]=1
    }, 
    [20]={
        ["log_name"]="loquacious earring", 
        ["id"]=14812, 
        ["name"]="loquac. earring", 
        ["count"]=1
    }, 
    [21]={
        ["log_name"]="luminary sash", 
        ["id"]=26329, 
        ["name"]="luminary sash", 
        ["count"]=1
    }, 
    [22]={
        ["log_name"]="chaac belt", 
        ["id"]=28450, 
        ["name"]="chaac belt", 
        ["count"]=1
    }, 
    [23]={
        ["log_name"]="bathy choker +1", 
        ["count"]=1, 
        ["id"]=27518, 
        ["name"]="bathy choker +1", 
        ["augments"]={
            [1]="Path: A"
        }
    }, 
    [24]={
        ["log_name"]="hypaspist earring", 
        ["id"]=26079, 
        ["name"]="hypaspist earring", 
        ["count"]=1
    }, 
    [25]={
        ["log_name"]="loricate torque +1", 
        ["count"]=1, 
        ["id"]=26002, 
        ["name"]="loricate torque +1", 
        ["augments"]={
            [1]="Path: A"
        }
    }, 
    [26]={
        ["log_name"]="neo animator", 
        ["id"]=21433, 
        ["name"]="neo animator", 
        ["count"]=1
    }, 
    [27]={
        ["log_name"]="animator p ii +1", 
        ["id"]=21459, 
        ["name"]="animator p ii +1", 
        ["count"]=1
    }, 
    [28]={
        ["log_name"]="warden's ring", 
        ["id"]=27555, 
        ["name"]="warden's ring", 
        ["count"]=1
    }, 
    [29]={
        ["log_name"]="animator p +1", 
        ["id"]=21457, 
        ["name"]="animator p +1", 
        ["count"]=1
    }, 
    [30]={
        ["log_name"]="dedition earring", 
        ["id"]=27544, 
        ["name"]="dedition earring", 
        ["count"]=1
    }, 
    [31]={
        ["log_name"]="nicander's necklace", 
        ["id"]=26086, 
        ["name"]="nicander's necklace", 
        ["count"]=1
    }, 
    [32]={
        ["log_name"]="etiolation earring", 
        ["id"]=28478, 
        ["name"]="etiolation earring", 
        ["count"]=1
    }, 
    [33]={
        ["log_name"]="carrier's sash", 
        ["id"]=10832, 
        ["name"]="carrier's sash", 
        ["count"]=1
    }, 
    [34]={
        ["log_name"]="siegel sash", 
        ["id"]=15960, 
        ["name"]="siegel sash", 
        ["count"]=1
    }, 
    [35]={
        ["log_name"]="confectioner's ring", 
        ["id"]=26224, 
        ["name"]="confectioner's ring", 
        ["count"]=1
    }, 
    [36]={
        ["log_name"]="handler's earring +1", 
        ["id"]=28491, 
        ["name"]="handler's earring +1", 
        ["count"]=1
    }, 
    [37]={
        ["log_name"]="metamorph ring +1", 
        ["count"]=1, 
        ["id"]=27563, 
        ["name"]="metamor. ring +1", 
        ["augments"]={
            [1]="Path: A"
        }
    }
}