-- Generated by the Organizer Library (Sun Mar 16 01:01:59 2025)
return {
    [1]={
        ["log_name"]="baetyl pendant", 
        ["id"]=26003, 
        ["name"]="baetyl pendant", 
        ["count"]=1
    }, 
    [2]={
        ["log_name"]="hetairoi ring", 
        ["id"]=26175, 
        ["name"]="hetairoi ring", 
        ["count"]=1
    }, 
    [3]={
        ["log_name"]="purity ring", 
        ["id"]=27554, 
        ["name"]="purity ring", 
        ["count"]=1
    }, 
    [4]={
        ["log_name"]="nefarious collar +1", 
        ["id"]=28365, 
        ["name"]="nefarious collar +1", 
        ["count"]=1
    }, 
    [5]={
        ["log_name"]="vengeful ring", 
        ["id"]=27592, 
        ["name"]="vengeful ring", 
        ["count"]=1
    }, 
    [6]={
        ["log_name"]="mendicant's earring", 
        ["id"]=28474, 
        ["name"]="mendi. earring", 
        ["count"]=1
    }, 
    [7]={
        ["log_name"]="blenmot's ring +1", 
        ["id"]=10795, 
        ["name"]="blenmot's ring +1", 
        ["count"]=1
    }, 
    [8]={
        ["log_name"]="paguroidea ring", 
        ["id"]=10753, 
        ["name"]="paguroidea ring", 
        ["count"]=1
    }, 
    [9]={
        ["log_name"]="sheltered ring", 
        ["id"]=10764, 
        ["name"]="sheltered ring", 
        ["count"]=1
    }, 
    [10]={
        ["log_name"]="hachirin-no-obi", 
        ["id"]=28419, 
        ["name"]="hachirin-no-obi", 
        ["count"]=1
    }, 
    [11]={
        ["log_name"]="gishdubar sash", 
        ["id"]=26323, 
        ["name"]="gishdubar sash", 
        ["count"]=1
    }, 
    [12]={
        ["log_name"]="fortified ring", 
        ["id"]=10773, 
        ["name"]="fortified ring", 
        ["count"]=1
    }, 
    [13]={
        ["log_name"]="ethereal earring", 
        ["id"]=15965, 
        ["name"]="ethereal earring", 
        ["count"]=1
    }, 
    [14]={
        ["log_name"]="flume belt +1", 
        ["id"]=28437, 
        ["name"]="flume belt +1", 
        ["count"]=1
    }, 
    [15]={
        ["log_name"]="petrov ring", 
        ["id"]=10772, 
        ["name"]="petrov ring", 
        ["count"]=1
    }, 
    [16]={
        ["log_name"]="beithir ring", 
        ["count"]=1, 
        ["id"]=26218, 
        ["name"]="beithir ring", 
        ["augments"]={
            [1]="Path: A"
        }
    }, 
    [17]={
        ["log_name"]="rahab ring", 
        ["id"]=26162, 
        ["name"]="rahab ring", 
        ["count"]=1
    }, 
    [18]={
        ["log_name"]="cryptic earring", 
        ["id"]=28483, 
        ["name"]="cryptic earring", 
        ["count"]=1
    }
}