-- Generated by the Organizer Library (Sun Nov 16 12:49:48 2025)
return {
    [1]={
        ["log_name"]="aurist's cape +1", 
        ["count"]=1, 
        ["id"]=27620, 
        ["name"]="aurist's cape +1", 
        ["augments"]={
            [1]="Path: A"
        }
    }, 
    [2]={
        ["log_name"]="kurys gloves", 
        ["id"]=27134, 
        ["name"]="kurys gloves", 
        ["count"]=1
    }, 
    [3]={
        ["log_name"]="solemnity cape", 
        ["id"]=26245, 
        ["name"]="solemnity cape", 
        ["count"]=1
    }, 
    [4]={
        ["log_name"]="moonlight cape", 
        ["id"]=26269, 
        ["name"]="moonlight cape", 
        ["count"]=1
    }, 
    [5]={
        ["log_name"]="fi follet cape +1", 
        ["count"]=1, 
        ["id"]=27610, 
        ["name"]="fi follet cape +1", 
        ["augments"]={
            [1]="Path: A"
        }
    }, 
    [6]={
        ["log_name"]="caduceus", 
        ["id"]=17058, 
        ["name"]="caduceus", 
        ["count"]=1
    }, 
    [7]={
        ["log_name"]="sacro mantle", 
        ["id"]=26270, 
        ["name"]="sacro mantle", 
        ["count"]=1
    }, 
    [8]={
        ["log_name"]="dispersal mantle", 
        ["count"]=1, 
        ["id"]=28634, 
        ["name"]="dispersal mantle", 
        ["augments"]={
            [1]="STR+1", 
            [2]="Pet: TP Bonus+480"
        }
    }, 
    [9]={
        ["log_name"]="grapevine cape", 
        ["id"]=11575, 
        ["name"]="grapevine cape", 
        ["count"]=1
    }, 
    [10]={
        ["log_name"]="reiki cloak", 
        ["id"]=27615, 
        ["name"]="reiki cloak", 
        ["count"]=1
    }, 
    [11]={
        ["log_name"]="argochampsa mantle", 
        ["id"]=27595, 
        ["name"]="argocham. mantle", 
        ["count"]=1
    }, 
    [12]={
        ["log_name"]="null shawl", 
        ["id"]=26274, 
        ["name"]="null shawl", 
        ["count"]=1
    }, 
    [13]={
        ["log_name"]="visucius's mantle", 
        ["count"]=1, 
        ["id"]=26263, 
        ["name"]="visucius's mantle", 
        ["augments"]={
            [1]="Pet: Acc.+20 Pet: R.Acc.+20 Pet: Atk.+20 Pet: R.Atk.+20", 
            [2]="Accuracy+20 Attack+20", 
            [3]="Pet: Attack+10 Pet: Rng.Atk.+10", 
            [4]="Pet: Haste+10"
        }
    }, 
    [14]={
        ["log_name"]="visucius's mantle", 
        ["count"]=1, 
        ["id"]=26263, 
        ["name"]="visucius's mantle", 
        ["augments"]={
            [1]="STR+20", 
            [2]="Accuracy+20 Attack+20", 
            [3]="STR+10", 
            [4]="\"Dbl.Atk.\"+10", 
            [5]="Phys. dmg. taken-10%"
        }
    }
}