-- Generated by the Organizer Library (Sun Mar 16 01:01:59 2025)
return {
    [1]={
        ["log_name"]="loquacious earring", 
        ["id"]=14812, 
        ["name"]="loquac. earring", 
        ["count"]=1
    }, 
    [2]={
        ["log_name"]="crepuscular earring", 
        ["id"]=26117, 
        ["name"]="crep. earring", 
        ["count"]=1
    }, 
    [3]={
        ["log_name"]="fotia belt", 
        ["id"]=28420, 
        ["name"]="fotia belt", 
        ["count"]=1
    }, 
    [4]={
        ["log_name"]="shadow ring", 
        ["id"]=14646, 
        ["name"]="shadow ring", 
        ["count"]=1
    }, 
    [5]={
        ["log_name"]="sailfi belt +1", 
        ["count"]=1, 
        ["id"]=28428, 
        ["name"]="sailfi belt +1", 
        ["augments"]={
            [1]="Path: A"
        }
    }, 
    [6]={
        ["log_name"]="rufescent ring", 
        ["id"]=26171, 
        ["name"]="rufescent ring", 
        ["count"]=1
    }, 
    [7]={
        ["log_name"]="incanter's torque", 
        ["id"]=26016, 
        ["name"]="incanter's torque", 
        ["count"]=1
    }, 
    [8]={
        ["log_name"]="siegel sash", 
        ["id"]=15960, 
        ["name"]="siegel sash", 
        ["count"]=1
    }, 
    [9]={
        ["log_name"]="niqmaddu ring", 
        ["id"]=26185, 
        ["name"]="niqmaddu ring", 
        ["count"]=1
    }, 
    [10]={
        ["log_name"]="dignitary's earring", 
        ["id"]=27547, 
        ["name"]="digni. earring", 
        ["count"]=1
    }, 
    [11]={
        ["log_name"]="olympus sash", 
        ["id"]=10821, 
        ["name"]="olympus sash", 
        ["count"]=1
    }, 
    [12]={
        ["log_name"]="trux earring", 
        ["id"]=28515, 
        ["name"]="trux earring", 
        ["count"]=1
    }, 
    [13]={
        ["log_name"]="metamorph ring +1", 
        ["count"]=1, 
        ["id"]=27563, 
        ["name"]="metamor. ring +1", 
        ["augments"]={
            [1]="Path: A"
        }
    }, 
    [14]={
        ["log_name"]="regal ring", 
        ["id"]=26191, 
        ["name"]="regal ring", 
        ["count"]=1
    }, 
    [15]={
        ["log_name"]="archon ring", 
        ["id"]=11674, 
        ["name"]="archon ring", 
        ["count"]=1
    }, 
    [16]={
        ["log_name"]="schere earring", 
        ["count"]=1, 
        ["id"]=26116, 
        ["name"]="schere earring", 
        ["augments"]={
            [1]="Path: A"
        }
    }, 
    [17]={
        ["log_name"]="apeile ring +1", 
        ["count"]=1, 
        ["id"]=27561, 
        ["name"]="apeile ring +1", 
        ["augments"]={
            [1]="Path: A"
        }
    }, 
    [18]={
        ["log_name"]="republican platinum medal", 
        ["id"]=25415, 
        ["name"]="rep. plat. medal", 
        ["count"]=1
    }, 
    [19]={
        ["log_name"]="chaac belt", 
        ["id"]=28450, 
        ["name"]="chaac belt", 
        ["count"]=1
    }, 
    [20]={
        ["log_name"]="kishar ring", 
        ["id"]=26188, 
        ["name"]="kishar ring", 
        ["count"]=1
    }, 
    [21]={
        ["log_name"]="moonlight necklace", 
        ["id"]=26037, 
        ["name"]="moonlight necklace", 
        ["count"]=1
    }, 
    [22]={
        ["log_name"]="haven hose", 
        ["id"]=11949, 
        ["name"]="haven hose", 
        ["count"]=1
    }, 
    [23]={
        ["log_name"]="loricate torque +1", 
        ["count"]=1, 
        ["id"]=26002, 
        ["name"]="loricate torque +1", 
        ["augments"]={
            [1]="Path: A"
        }
    }, 
    [24]={
        ["log_name"]="warden's ring", 
        ["id"]=27555, 
        ["name"]="warden's ring", 
        ["count"]=1
    }, 
    [25]={
        ["log_name"]="brutal earring", 
        ["id"]=14813, 
        ["name"]="brutal earring", 
        ["count"]=1
    }, 
    [26]={
        ["log_name"]="dedition earring", 
        ["id"]=27544, 
        ["name"]="dedition earring", 
        ["count"]=1
    }, 
    [27]={
        ["log_name"]="nicander's necklace", 
        ["id"]=26086, 
        ["name"]="nicander's necklace", 
        ["count"]=1
    }, 
    [28]={
        ["log_name"]="apeile ring", 
        ["id"]=27560, 
        ["name"]="apeile ring", 
        ["count"]=1
    }, 
    [29]={
        ["log_name"]="macabre gauntlets +1", 
        ["id"]=27994, 
        ["name"]="macabre gaunt. +1", 
        ["count"]=1
    }, 
    [30]={
        ["log_name"]="eabani earring", 
        ["id"]=27540, 
        ["name"]="eabani earring", 
        ["count"]=1
    }, 
    [31]={
        ["log_name"]="mache earring +1", 
        ["id"]=26081, 
        ["name"]="mache earring +1", 
        ["count"]=1
    }, 
    [32]={
        ["log_name"]="erra pendant", 
        ["id"]=26030, 
        ["name"]="erra pendant", 
        ["count"]=1
    }, 
    [33]={
        ["log_name"]="ioskeha belt +1", 
        ["id"]=26334, 
        ["name"]="ioskeha belt +1", 
        ["count"]=1
    }, 
    [34]={
        ["log_name"]="goldsmith's torque", 
        ["id"]=10950, 
        ["name"]="goldsm. torque", 
        ["count"]=1
    }, 
    [35]={
        ["log_name"]="bathy choker +1", 
        ["count"]=1, 
        ["id"]=27518, 
        ["name"]="bathy choker +1", 
        ["augments"]={
            [1]="Path: A"
        }
    }, 
    [36]={
        ["log_name"]="mephitas's ring +1", 
        ["count"]=1, 
        ["id"]=27559, 
        ["name"]="mephitas's ring +1", 
        ["augments"]={
            [1]="Path: A"
        }
    }, 
    [37]={
        ["log_name"]="cornelia's ring", 
        ["id"]=26227, 
        ["name"]="cornelia's ring", 
        ["count"]=1
    }
}