-- Generated by the Organizer Library (Sun Mar 16 01:01:59 2025)
return {
    [1]={
        ["log_name"]="magoraga bead necklace", 
        ["id"]=11627, 
        ["name"]="magoraga beads", 
        ["count"]=1
    }, 
    [2]={
        ["log_name"]="null belt", 
        ["id"]=26367, 
        ["name"]="null belt", 
        ["count"]=1
    }, 
    [3]={
        ["log_name"]="ainia collar", 
        ["id"]=26020, 
        ["name"]="ainia collar", 
        ["count"]=1
    }, 
    [4]={
        ["log_name"]="sakpata's gauntlets", 
        ["count"]=1, 
        ["id"]=23771, 
        ["name"]="sakpata's gauntlets", 
        ["augments"]={
            [1]="Path: A"
        }
    }, 
    [5]={
        ["log_name"]="null loop", 
        ["id"]=26042, 
        ["name"]="null loop", 
        ["count"]=1
    }, 
    [6]={
        ["log_name"]="sacro breastplate", 
        ["id"]=25767, 
        ["name"]="sacro breastplate", 
        ["count"]=1
    }, 
    [7]={
        ["log_name"]="zoar subligar +1", 
        ["count"]=1, 
        ["id"]=27231, 
        ["name"]="zoar subligar +1", 
        ["augments"]={
            [1]="Path: A"
        }
    }, 
    [8]={
        ["log_name"]="odyssean greaves", 
        ["count"]=1, 
        ["id"]=27494, 
        ["name"]="odyssean greaves", 
        ["augments"]={
            [1]="\"Mag.Atk.Bns.\"+23", 
            [2]="Magic dmg. taken -5%", 
            [3]="INT+9"
        }
    }, 
    [9]={
        ["log_name"]="sroda ring", 
        ["id"]=26221, 
        ["name"]="sroda ring", 
        ["count"]=1
    }, 
    [10]={
        ["log_name"]="hermes' sandals +1", 
        ["id"]=11380, 
        ["name"]="hermes' sandals +1", 
        ["count"]=1
    }, 
    [11]={
        ["log_name"]="blistering sallet +1", 
        ["count"]=1, 
        ["id"]=25602, 
        ["name"]="blistering sallet +1", 
        ["augments"]={
            [1]="Path: A"
        }
    }, 
    [12]={
        ["log_name"]="sakpata's leggings", 
        ["count"]=1, 
        ["id"]=23785, 
        ["name"]="sakpata's leggings", 
        ["augments"]={
            [1]="Path: A"
        }
    }, 
    [13]={
        ["log_name"]="souveran diechlings +1", 
        ["count"]=1, 
        ["id"]=27199, 
        ["name"]="souv. diechlings +1", 
        ["augments"]={
            [1]="HP+105", 
            [2]="Enmity+9", 
            [3]="Potency of \"Cure\" effect received +15%"
        }
    }, 
    [14]={
        ["log_name"]="sakpata's helm", 
        ["count"]=1, 
        ["id"]=23757, 
        ["name"]="sakpata's helm", 
        ["augments"]={
            [1]="Path: A"
        }
    }, 
    [15]={
        ["log_name"]="lugra earring +1", 
        ["count"]=1, 
        ["id"]=28482, 
        ["name"]="lugra earring +1", 
        ["augments"]={
            [1]="Path: A"
        }
    }, 
    [16]={
        ["log_name"]="acerbic sash +1", 
        ["id"]=28435, 
        ["name"]="acerbic sash +1", 
        ["count"]=1
    }, 
    [17]={
        ["log_name"]="debahocho +1", 
        ["id"]=21924, 
        ["name"]="debahocho +1", 
        ["count"]=1
    }, 
    [18]={
        ["log_name"]="dagon breastplate", 
        ["id"]=25785, 
        ["name"]="dagon breast.", 
        ["count"]=1
    }, 
    [19]={
        ["log_name"]="crepuscular ring", 
        ["id"]=26220, 
        ["name"]="crepuscular ring", 
        ["count"]=1
    }, 
    [20]={
        ["log_name"]="warrior's bead necklace +2", 
        ["count"]=1, 
        ["id"]=25419, 
        ["name"]="war. beads +2", 
        ["augments"]={
            [1]="Path: A"
        }
    }, 
    [21]={
        ["log_name"]="crepuscular pebble", 
        ["id"]=22300, 
        ["name"]="crepuscular pebble", 
        ["count"]=1
    }, 
    [22]={
        ["log_name"]="earthcry earring", 
        ["id"]=11037, 
        ["name"]="earthcry earring", 
        ["count"]=1
    }, 
    [23]={
        ["log_name"]="odyssean helm", 
        ["count"]=1, 
        ["id"]=25640, 
        ["name"]="odyssean helm", 
        ["augments"]={
            [1]="INT+5", 
            [2]="\"Cure\" potency +8%", 
            [3]="Phalanx +4", 
            [4]="Accuracy+15 Attack+15", 
            [5]="Mag. Acc.+7 \"Mag.Atk.Bns.\"+7"
        }
    }, 
    [24]={
        ["log_name"]="ikenga's axe", 
        ["id"]=21723, 
        ["name"]="ikenga's axe", 
        ["count"]=1
    }, 
    [25]={
        ["log_name"]="sakpata's cuisses", 
        ["count"]=1, 
        ["id"]=23778, 
        ["name"]="sakpata's cuisses", 
        ["augments"]={
            [1]="Path: A"
        }
    }, 
    [26]={
        ["log_name"]="odyssean cuisses", 
        ["count"]=1, 
        ["id"]=25840, 
        ["name"]="odyssean cuisses", 
        ["augments"]={
            [1]="Attack+29", 
            [2]="\"Fast Cast\"+5", 
            [3]="CHR+10"
        }
    }, 
    [27]={
        ["log_name"]="amar cluster", 
        ["id"]=22262, 
        ["name"]="amar cluster", 
        ["count"]=1
    }, 
    [28]={
        ["log_name"]="defending ring", 
        ["id"]=13566, 
        ["name"]="defending ring", 
        ["count"]=1
    }, 
    [29]={
        ["log_name"]="null masuqe", 
        ["id"]=24270, 
        ["name"]="null masque", 
        ["count"]=1
    }, 
    [30]={
        ["log_name"]="pixie hairpin +1", 
        ["id"]=26696, 
        ["name"]="pixie hairpin +1", 
        ["count"]=1
    }, 
    [31]={
        ["log_name"]="fotia gorget", 
        ["id"]=27510, 
        ["name"]="fotia gorget", 
        ["count"]=1
    }, 
    [32]={
        ["log_name"]="stone gorget", 
        ["id"]=13177, 
        ["name"]="stone gorget", 
        ["count"]=1
    }, 
    [33]={
        ["log_name"]="sakpata's breastplate", 
        ["count"]=1, 
        ["id"]=23764, 
        ["name"]="sakpata's plate", 
        ["augments"]={
            [1]="Path: A"
        }
    }, 
    [34]={
        ["log_name"]="iron gobbet", 
        ["id"]=19782, 
        ["name"]="iron gobbet", 
        ["count"]=1
    }, 
    [35]={
        ["log_name"]="souveran schuhs +1", 
        ["count"]=1, 
        ["id"]=27375, 
        ["name"]="souveran schuhs +1", 
        ["augments"]={
            [1]="HP+105", 
            [2]="Enmity+9", 
            [3]="Potency of \"Cure\" effect received +15%"
        }
    }, 
    [36]={
        ["id"]=10963, 
        ["name"]="airmid's gorget", 
        ["count"]=1, 
        ["log_name"]="airmid's gorget"
    }
}