-- Generated by the Organizer Library (Sun Nov 16 12:49:48 2025)
return {
    [1]={
        ["log_name"]="taeon tabard", 
        ["count"]=1, 
        ["id"]=26893, 
        ["name"]="taeon tabard", 
        ["augments"]={
            [1]="Phalanx +3"
        }
    }, 
    [2]={
        ["log_name"]="rumination sash", 
        ["id"]=28421, 
        ["name"]="rumination sash", 
        ["count"]=1
    }, 
    [3]={
        ["log_name"]="shulmanu collar", 
        ["id"]=26026, 
        ["name"]="shulmanu collar", 
        ["count"]=1
    }, 
    [4]={
        ["log_name"]="lissome necklace", 
        ["id"]=26004, 
        ["name"]="lissome necklace", 
        ["count"]=1
    }, 
    [5]={
        ["log_name"]="eschan stone", 
        ["id"]=28415, 
        ["name"]="eschan stone", 
        ["count"]=1
    }, 
    [6]={
        ["log_name"]="volte harness", 
        ["id"]=23715, 
        ["name"]="volte harness", 
        ["count"]=1
    }, 
    [7]={
        ["log_name"]="purity ring", 
        ["id"]=27554, 
        ["name"]="purity ring", 
        ["count"]=1
    }, 
    [8]={
        ["log_name"]="phalaina locket", 
        ["id"]=10960, 
        ["name"]="phalaina locket", 
        ["count"]=1
    }, 
    [9]={
        ["log_name"]="vengeful ring", 
        ["id"]=27592, 
        ["name"]="vengeful ring", 
        ["count"]=1
    }, 
    [10]={
        ["log_name"]="overbearing ring", 
        ["id"]=27552, 
        ["name"]="overbearing ring", 
        ["count"]=1
    }, 
    [11]={
        ["log_name"]="buremte gloves", 
        ["id"]=28050, 
        ["name"]="buremte gloves", 
        ["count"]=1
    }, 
    [12]={
        ["log_name"]="mache earring +1", 
        ["id"]=26081, 
        ["name"]="mache earring +1", 
        ["count"]=1
    }, 
    [13]={
        ["log_name"]="taeon tights", 
        ["count"]=1, 
        ["id"]=27234, 
        ["name"]="taeon tights", 
        ["augments"]={
            [1]="Phalanx +3"
        }
    }, 
    [14]={
        ["log_name"]="fortified ring", 
        ["id"]=10773, 
        ["name"]="fortified ring", 
        ["count"]=1
    }, 
    [15]={
        ["log_name"]="adad amulet", 
        ["id"]=26028, 
        ["name"]="adad amulet", 
        ["count"]=1
    }, 
    [16]={
        ["log_name"]="sheltered ring", 
        ["id"]=10764, 
        ["name"]="sheltered ring", 
        ["count"]=1
    }, 
    [17]={
        ["log_name"]="blenmot's ring +1", 
        ["id"]=10795, 
        ["name"]="blenmot's ring +1", 
        ["count"]=1
    }, 
    [18]={
        ["log_name"]="ethereal earring", 
        ["id"]=15965, 
        ["name"]="ethereal earring", 
        ["count"]=1
    }, 
    [19]={
        ["log_name"]="rimeice earring", 
        ["id"]=28495, 
        ["name"]="rimeice earring", 
        ["count"]=1
    }, 
    [20]={
        ["log_name"]="cath palug ring", 
        ["id"]=28473, 
        ["name"]="c. palug ring", 
        ["count"]=1
    }, 
    [21]={
        ["log_name"]="rahab ring", 
        ["id"]=26162, 
        ["name"]="rahab ring", 
        ["count"]=1
    }, 
    [22]={
        ["log_name"]="kunaji ring", 
        ["id"]=28577, 
        ["name"]="kunaji ring", 
        ["count"]=1
    }, 
    [23]={
        ["log_name"]="varar ring +1", 
        ["id"]=26180, 
        ["name"]="varar ring +1", 
        ["count"]=1
    }, 
    [24]={
        ["log_name"]="varar ring +1", 
        ["id"]=26180, 
        ["name"]="varar ring +1", 
        ["count"]=1
    }, 
    [25]={
        ["log_name"]="petrov ring", 
        ["id"]=10772, 
        ["name"]="petrov ring", 
        ["count"]=1
    }, 
    [26]={
        ["log_name"]="gishdubar sash", 
        ["id"]=26323, 
        ["name"]="gishdubar sash", 
        ["count"]=1
    }, 
    [27]={
        ["log_name"]="gere ring", 
        ["id"]=28471, 
        ["name"]="gere ring", 
        ["count"]=1
    }, 
    [28]={
        ["log_name"]="mendicant's earring", 
        ["id"]=28474, 
        ["name"]="mendi. earring", 
        ["count"]=1
    }, 
    [29]={
        ["id"]=17040, 
        ["name"]="warp cudgel", 
        ["count"]=1, 
        ["log_name"]="warp cudgel"
    }, 
    [30]={
        ["id"]=14790, 
        ["name"]="reraise earring", 
        ["count"]=1, 
        ["log_name"]="reraise earring"
    }
}