-- Generated by the Organizer Library (Sun Mar 16 01:01:59 2025)
return {
    [1]={
        ["log_name"]="nyame helm", 
        ["count"]=1, 
        ["id"]=23761, 
        ["name"]="nyame helm", 
        ["augments"]={
            [1]="Path: B"
        }
    }, 
    [2]={
        ["log_name"]="goldsmith's ring", 
        ["id"]=15821, 
        ["name"]="goldsmith's ring", 
        ["count"]=1
    }, 
    [3]={
        ["log_name"]="hjarrandi breastplate", 
        ["id"]=25766, 
        ["name"]="hjarrandi breast.", 
        ["count"]=1
    }, 
    [4]={
        ["log_name"]="nyame flanchard", 
        ["count"]=1, 
        ["id"]=23782, 
        ["name"]="nyame flanchard", 
        ["augments"]={
            [1]="Path: B"
        }
    }, 
    [5]={
        ["log_name"]="utu grip", 
        ["id"]=22212, 
        ["name"]="utu grip", 
        ["count"]=1
    }, 
    [6]={
        ["log_name"]="stikini ring +1", 
        ["id"]=26184, 
        ["name"]="stikini ring +1", 
        ["count"]=1
    }, 
    [7]={
        ["log_name"]="stikini ring +1", 
        ["id"]=26184, 
        ["name"]="stikini ring +1", 
        ["count"]=1
    }, 
    [8]={
        ["log_name"]="firangi", 
        ["id"]=20678, 
        ["name"]="firangi", 
        ["count"]=1
    }, 
    [9]={
        ["log_name"]="shaded spectacles", 
        ["id"]=13945, 
        ["name"]="shaded specs.", 
        ["count"]=1
    }, 
    [10]={
        ["log_name"]="hjarrandi helm", 
        ["id"]=25592, 
        ["name"]="hjarrandi helm", 
        ["count"]=1
    }, 
    [11]={
        ["log_name"]="knobkierrie", 
        ["id"]=22281, 
        ["name"]="knobkierrie", 
        ["count"]=1
    }, 
    [12]={
        ["log_name"]="malevolence", 
        ["id"]=20595, 
        ["name"]="malevolence", 
        ["count"]=1
    }, 
    [13]={
        ["log_name"]="malevolence", 
        ["id"]=20595, 
        ["name"]="malevolence", 
        ["count"]=1
    }, 
    [14]={
        ["log_name"]="souveran cuirass +1", 
        ["count"]=1, 
        ["id"]=26847, 
        ["name"]="souv. cuirass +1", 
        ["augments"]={
            [1]="HP+105", 
            [2]="Enmity+9", 
            [3]="Potency of \"Cure\" effect received +15%"
        }
    }, 
    [15]={
        ["log_name"]="friomisi earring", 
        ["id"]=28514, 
        ["name"]="friomisi earring", 
        ["count"]=1
    }, 
    [16]={
        ["log_name"]="ishvara earring", 
        ["id"]=27537, 
        ["name"]="ishvara earring", 
        ["count"]=1
    }, 
    [17]={
        ["log_name"]="pemphredo tathlum", 
        ["id"]=22271, 
        ["name"]="pemphredo tathlum", 
        ["count"]=1
    }, 
    [18]={
        ["log_name"]="shabti cuirass +1", 
        ["id"]=27892, 
        ["name"]="shab. cuirass +1", 
        ["count"]=1
    }, 
    [19]={
        ["log_name"]="craftmaster's ring", 
        ["id"]=28586, 
        ["name"]="craftmaster's ring", 
        ["count"]=1
    }, 
    [20]={
        ["log_name"]="coiste bodhar", 
        ["count"]=1, 
        ["id"]=21431, 
        ["name"]="coiste bodhar", 
        ["augments"]={
            [1]="Path: A"
        }
    }, 
    [21]={
        ["log_name"]="craftkeeper's ring", 
        ["id"]=28585, 
        ["name"]="craftkeeper's ring", 
        ["count"]=1
    }, 
    [22]={
        ["log_name"]="orvail ring +1", 
        ["id"]=26203, 
        ["name"]="orvail ring +1", 
        ["count"]=1
    }, 
    [23]={
        ["log_name"]="moonshade earring", 
        ["count"]=1, 
        ["id"]=11697, 
        ["name"]="moonshade earring", 
        ["augments"]={
            [1]="Accuracy+4", 
            [2]="TP Bonus +250"
        }
    }, 
    [24]={
        ["log_name"]="telos earring", 
        ["id"]=27545, 
        ["name"]="telos earring", 
        ["count"]=1
    }, 
    [25]={
        ["log_name"]="suit of adamantite armor", 
        ["id"]=23861, 
        ["name"]="adamantite armor", 
        ["count"]=1
    }, 
    [26]={
        ["log_name"]="nyame gauntlets", 
        ["count"]=1, 
        ["id"]=23775, 
        ["name"]="nyame gauntlets", 
        ["augments"]={
            [1]="Path: B"
        }
    }, 
    [27]={
        ["log_name"]="staunch tathlum +1", 
        ["id"]=22279, 
        ["name"]="staunch tathlum +1", 
        ["count"]=1
    }, 
    [28]={
        ["log_name"]="nyame sollerets", 
        ["count"]=1, 
        ["id"]=23789, 
        ["name"]="nyame sollerets", 
        ["augments"]={
            [1]="Path: B"
        }
    }, 
    [29]={
        ["log_name"]="andoaa earring", 
        ["id"]=28506, 
        ["name"]="andoaa earring", 
        ["count"]=1
    }, 
    [30]={
        ["log_name"]="nyame mail", 
        ["count"]=1, 
        ["id"]=23768, 
        ["name"]="nyame mail", 
        ["augments"]={
            [1]="Path: B"
        }
    }, 
    [31]={
        ["log_name"]="adapa shield", 
        ["id"]=26420, 
        ["name"]="adapa shield", 
        ["count"]=1
    }, 
    [32]={
        ["log_name"]="souveran handschuhs +1", 
        ["count"]=1, 
        ["id"]=27023, 
        ["name"]="souv. handsch. +1", 
        ["augments"]={
            [1]="HP+105", 
            [2]="Enmity+9", 
            [3]="Potency of \"Cure\" effect received +15%"
        }
    }, 
    [33]={
        ["log_name"]="crepuscular helm", 
        ["id"]=23797, 
        ["name"]="crepuscular helm", 
        ["count"]=1
    }, 
    [34]={
        ["log_name"]="ghastly tathlum +1", 
        ["count"]=1, 
        ["id"]=21344, 
        ["name"]="ghastly tathlum +1", 
        ["augments"]={
            [1]="Path: A"
        }
    }, 
    [35]={
        ["log_name"]="thrud earring", 
        ["id"]=26107, 
        ["name"]="thrud earring", 
        ["count"]=1
    }
}