-- Generated by the Organizer Library (Sun Mar 16 01:01:59 2025)
return {
    [1]={
        ["log_name"]="zanmato +1", 
        ["id"]=21966, 
        ["name"]="zanmato +1", 
        ["count"]=1
    }, 
    [2]={
        ["log_name"]="maven's scythe", 
        ["id"]=21840, 
        ["name"]="maven's scythe", 
        ["count"]=1
    }, 
    [3]={
        ["log_name"]="sha wujing's lance +1", 
        ["id"]=21868, 
        ["name"]="sha wujing's la. +1", 
        ["count"]=1
    }, 
    [4]={
        ["log_name"]="drepanum", 
        ["id"]=21830, 
        ["name"]="drepanum", 
        ["count"]=1
    }, 
    [5]={
        ["log_name"]="loxotic mace +1", 
        ["id"]=21091, 
        ["name"]="loxotic mace +1", 
        ["count"]=1
    }, 
    [6]={
        ["log_name"]="agwu's claymore", 
        ["id"]=21675, 
        ["name"]="agwu's claymore", 
        ["count"]=1
    }, 
    [7]={
        ["log_name"]="irradiance blade", 
        ["id"]=21693, 
        ["name"]="irradiance blade", 
        ["count"]=1
    }, 
    [8]={
        ["log_name"]="blurred shield +1", 
        ["id"]=27644, 
        ["name"]="blurred shield +1", 
        ["count"]=1
    }, 
    [9]={
        ["log_name"]="chango", 
        ["id"]=20843, 
        ["name"]="chango", 
        ["count"]=1
    }, 
    [10]={
        ["log_name"]="toreutic escutcheon", 
        ["id"]=26437, 
        ["name"]="tr. escutcheon", 
        ["count"]=1
    }, 
    [11]={
        ["log_name"]="naegling", 
        ["id"]=21621, 
        ["name"]="naegling", 
        ["count"]=1
    }, 
    [12]={
        ["log_name"]="fermion sword", 
        ["id"]=20694, 
        ["name"]="fermion sword", 
        ["count"]=1
    }, 
    [13]={
        ["log_name"]="reikiko", 
        ["id"]=20690, 
        ["name"]="reikiko", 
        ["count"]=1
    }, 
    [14]={
        ["log_name"]="shining one", 
        ["id"]=21883, 
        ["name"]="shining one", 
        ["count"]=1
    }, 
    [15]={
        ["log_name"]="sacro bulwark", 
        ["id"]=26487, 
        ["name"]="sacro bulwark", 
        ["count"]=1
    }, 
    [16]={
        ["log_name"]="demersal degen +1", 
        ["id"]=20709, 
        ["name"]="demers. degen +1", 
        ["count"]=1
    }
}