-- Automatically generated file: Weapon Skills

return {
    ['Combo'] = {id=1,en="Combo",ja="コンボ",element=6,icon_id=590,prefix="/weaponskill",range=7,skill=1,skillchain_a="Impaction",skillchain_b="",skillchain_c="",targets=32},
    ['Shoulder Tackle'] = {id=2,en="Shoulder Tackle",ja="タックル",element=4,icon_id=591,prefix="/weaponskill",range=7,skill=1,skillchain_a="Impaction",skillchain_b="Reverberation",skillchain_c="",targets=32},
    ['One Inch Punch'] = {id=3,en="One Inch Punch",ja="短勁",element=6,icon_id=590,prefix="/weaponskill",range=7,skill=1,skillchain_a="Compression",skillchain_b="",skillchain_c="",targets=32},
    ['Backhand Blow'] = {id=4,en="Backhand Blow",ja="バックハンドブロー",element=6,icon_id=590,prefix="/weaponskill",range=7,skill=1,skillchain_a="Detonation",skillchain_b="",skillchain_c="",targets=32},
    ['Raging Fists'] = {id=5,en="Raging Fists",ja="乱撃",element=6,icon_id=590,prefix="/weaponskill",range=7,skill=1,skillchain_a="Impaction",skillchain_b="",skillchain_c="",targets=32},
    ['Spinning Attack'] = {id=6,en="Spinning Attack",ja="スピンアタック",element=6,icon_id=590,prefix="/weaponskill",range=7,skill=1,skillchain_a="Liquefaction",skillchain_b="Impaction",skillchain_c="",targets=32},
    ['Howling Fist'] = {id=7,en="Howling Fist",ja="空鳴拳",element=6,icon_id=590,prefix="/weaponskill",range=7,skill=1,skillchain_a="Transfixion",skillchain_b="Impaction",skillchain_c="",targets=32},
    ['Dragon Kick'] = {id=8,en="Dragon Kick",ja="双竜脚",element=6,icon_id=590,prefix="/weaponskill",range=7,skill=1,skillchain_a="Fragmentation",skillchain_b="",skillchain_c="",targets=32},
    ['Asuran Fists'] = {id=9,en="Asuran Fists",ja="夢想阿修羅拳",element=6,icon_id=590,prefix="/weaponskill",range=7,skill=1,skillchain_a="Gravitation",skillchain_b="Liquefaction",skillchain_c="",targets=32},
    ['Final Heaven'] = {id=10,en="Final Heaven",ja="ファイナルヘヴン",element=6,icon_id=590,prefix="/weaponskill",range=7,skill=1,skillchain_a="Light",skillchain_b="Fusion",skillchain_c="",targets=32},
    ['Ascetic\'s Fury'] = {id=11,en="Ascetic's Fury",ja="アスケーテンツォルン",element=6,icon_id=590,prefix="/weaponskill",range=7,skill=1,skillchain_a="Fusion",skillchain_b="Transfixion",skillchain_c="",targets=32},
    ['Stringing Pummel'] = {id=12,en="Stringing Pummel",ja="連環六合圏",element=6,icon_id=590,prefix="/weaponskill",range=7,skill=1,skillchain_a="Gravitation",skillchain_b="Liquefaction",skillchain_c="",targets=32},
    ['Tornado Kick'] = {id=13,en="Tornado Kick",ja="闘魂旋風脚",element=6,icon_id=590,prefix="/weaponskill",range=7,skill=1,skillchain_a="Induration",skillchain_b="Impaction",skillchain_c="Detonation",targets=32},
    ['Victory Smite'] = {id=14,en="Victory Smite",ja="ビクトリースマイト",element=6,icon_id=590,prefix="/weaponskill",range=7,skill=1,skillchain_a="Light",skillchain_b="Fragmentation",skillchain_c="",targets=32},
    ['Shijin Spiral'] = {id=15,en="Shijin Spiral",ja="四神円舞",element=0,icon_id=592,prefix="/weaponskill",range=7,skill=1,skillchain_a="Fusion",skillchain_b="Reverberation",skillchain_c="",targets=32},
    ['Wasp Sting'] = {id=16,en="Wasp Sting",ja="ワスプスティング",element=5,icon_id=593,prefix="/weaponskill",range=7,skill=2,skillchain_a="Scission",skillchain_b="",skillchain_c="",targets=32},
    ['Viper Bite'] = {id=17,en="Viper Bite",ja="バイパーバイト",element=5,icon_id=593,prefix="/weaponskill",range=7,skill=2,skillchain_a="Scission",skillchain_b="",skillchain_c="",targets=32},
    ['Shadowstitch'] = {id=18,en="Shadowstitch",ja="シャドーステッチ",element=1,icon_id=594,prefix="/weaponskill",range=7,skill=2,skillchain_a="Reverberation",skillchain_b="",skillchain_c="",targets=32},
    ['Gust Slash'] = {id=19,en="Gust Slash",ja="ガストスラッシュ",element=2,icon_id=595,prefix="/weaponskill",range=10,skill=2,skillchain_a="Detonation",skillchain_b="",skillchain_c="",targets=32},
    ['Cyclone'] = {id=20,en="Cyclone",ja="サイクロン",element=2,icon_id=595,prefix="/weaponskill",range=10,skill=2,skillchain_a="Detonation",skillchain_b="Impaction",skillchain_c="",targets=32},
    ['Energy Steal'] = {id=21,en="Energy Steal",ja="エナジースティール",element=7,icon_id=596,prefix="/weaponskill",range=7,skill=2,skillchain_a="",skillchain_b="",skillchain_c="",targets=32},
    ['Energy Drain'] = {id=22,en="Energy Drain",ja="エナジードレイン",element=7,icon_id=596,prefix="/weaponskill",range=7,skill=2,skillchain_a="",skillchain_b="",skillchain_c="",targets=32},
    ['Dancing Edge'] = {id=23,en="Dancing Edge",ja="ダンシングエッジ",element=6,icon_id=597,prefix="/weaponskill",range=7,skill=2,skillchain_a="Scission",skillchain_b="Detonation",skillchain_c="",targets=32},
    ['Shark Bite'] = {id=24,en="Shark Bite",ja="シャークバイト",element=6,icon_id=597,prefix="/weaponskill",range=7,skill=2,skillchain_a="Fragmentation",skillchain_b="",skillchain_c="",targets=32},
    ['Evisceration'] = {id=25,en="Evisceration",ja="エヴィサレーション",element=6,icon_id=597,prefix="/weaponskill",range=7,skill=2,skillchain_a="Gravitation",skillchain_b="Transfixion",skillchain_c="",targets=32},
    ['Mercy Stroke'] = {id=26,en="Mercy Stroke",ja="マーシーストローク",element=6,icon_id=597,prefix="/weaponskill",range=7,skill=2,skillchain_a="Darkness",skillchain_b="Gravitation",skillchain_c="",targets=32},
    ['Mandalic Stab'] = {id=27,en="Mandalic Stab",ja="マンダリクスタッブ",element=6,icon_id=597,prefix="/weaponskill",range=7,skill=2,skillchain_a="Fusion",skillchain_b="Compression",skillchain_c="",targets=32},
    ['Mordant Rime'] = {id=28,en="Mordant Rime",ja="モーダントライム",element=2,icon_id=595,prefix="/weaponskill",range=7,skill=2,skillchain_a="Fragmentation",skillchain_b="Distortion",skillchain_c="",targets=32},
    ['Pyrrhic Kleos'] = {id=29,en="Pyrrhic Kleos",ja="ピリッククレオス",element=1,icon_id=594,prefix="/weaponskill",range=7,skill=2,skillchain_a="Distortion",skillchain_b="Scission",skillchain_c="",targets=32},
    ['Aeolian Edge'] = {id=30,en="Aeolian Edge",ja="イオリアンエッジ",element=2,icon_id=595,prefix="/weaponskill",range=7,skill=2,skillchain_a="Impaction",skillchain_b="Scission",skillchain_c="Detonation",targets=32},
    ['Rudra\'s Storm'] = {id=31,en="Rudra's Storm",ja="ルドラストーム",element=2,icon_id=595,prefix="/weaponskill",range=7,skill=2,skillchain_a="Darkness",skillchain_b="Distortion",skillchain_c="",targets=32},
    ['Fast Blade'] = {id=32,en="Fast Blade",ja="ファストブレード",element=6,icon_id=598,prefix="/weaponskill",range=7,skill=3,skillchain_a="Scission",skillchain_b="",skillchain_c="",targets=32},
    ['Burning Blade'] = {id=33,en="Burning Blade",ja="バーニングブレード",element=0,icon_id=599,prefix="/weaponskill",range=7,skill=3,skillchain_a="Liquefaction",skillchain_b="",skillchain_c="",targets=32},
    ['Red Lotus Blade'] = {id=34,en="Red Lotus Blade",ja="レッドロータス",element=0,icon_id=599,prefix="/weaponskill",range=7,skill=3,skillchain_a="Liquefaction",skillchain_b="Detonation",skillchain_c="",targets=32},
    ['Flat Blade'] = {id=35,en="Flat Blade",ja="フラットブレード",element=4,icon_id=600,prefix="/weaponskill",range=7,skill=3,skillchain_a="Impaction",skillchain_b="",skillchain_c="",targets=32},
    ['Shining Blade'] = {id=36,en="Shining Blade",ja="シャインブレード",element=6,icon_id=598,prefix="/weaponskill",range=7,skill=3,skillchain_a="Scission",skillchain_b="",skillchain_c="",targets=32},
    ['Seraph Blade'] = {id=37,en="Seraph Blade",ja="セラフブレード",element=6,icon_id=598,prefix="/weaponskill",range=7,skill=3,skillchain_a="Scission",skillchain_b="",skillchain_c="",targets=32},
    ['Circle Blade'] = {id=38,en="Circle Blade",ja="サークルブレード",element=6,icon_id=598,prefix="/weaponskill",range=7,skill=3,skillchain_a="Reverberation",skillchain_b="Impaction",skillchain_c="",targets=32},
    ['Spirits Within'] = {id=39,en="Spirits Within",ja="スピリッツウィズイン",element=15,icon_id=598,prefix="/weaponskill",range=7,skill=3,skillchain_a="",skillchain_b="",skillchain_c="",targets=32},
    ['Vorpal Blade'] = {id=40,en="Vorpal Blade",ja="ボーパルブレード",element=6,icon_id=598,prefix="/weaponskill",range=7,skill=3,skillchain_a="Scission",skillchain_b="Impaction",skillchain_c="",targets=32},
    ['Swift Blade'] = {id=41,en="Swift Blade",ja="スウィフトブレード",element=6,icon_id=598,prefix="/weaponskill",range=7,skill=3,skillchain_a="Gravitation",skillchain_b="",skillchain_c="",targets=32},
    ['Savage Blade'] = {id=42,en="Savage Blade",ja="サベッジブレード",element=6,icon_id=598,prefix="/weaponskill",range=7,skill=3,skillchain_a="Fragmentation",skillchain_b="Scission",skillchain_c="",targets=32},
    ['Knights of Round'] = {id=43,en="Knights of Round",ja="ナイツオブラウンド",element=6,icon_id=598,prefix="/weaponskill",range=7,skill=3,skillchain_a="Light",skillchain_b="Fusion",skillchain_c="",targets=32},
    ['Death Blossom'] = {id=44,en="Death Blossom",ja="ロズレーファタール",element=4,icon_id=600,prefix="/weaponskill",range=7,skill=3,skillchain_a="Fragmentation",skillchain_b="Distortion",skillchain_c="",targets=32},
    ['Atonement'] = {id=45,en="Atonement",ja="ロイエ",element=15,icon_id=598,prefix="/weaponskill",range=7,skill=3,skillchain_a="Fusion",skillchain_b="Reverberation",skillchain_c="",targets=32},
    ['Expiacion'] = {id=46,en="Expiacion",ja="エクスピアシオン",element=6,icon_id=598,prefix="/weaponskill",range=7,skill=3,skillchain_a="Distortion",skillchain_b="Scission",skillchain_c="",targets=32},
    ['Sanguine Blade'] = {id=47,en="Sanguine Blade",ja="サンギンブレード",element=7,icon_id=601,prefix="/weaponskill",range=7,skill=3,skillchain_a="",skillchain_b="",skillchain_c="",targets=32},
    ['Hard Slash'] = {id=48,en="Hard Slash",ja="ハードスラッシュ",element=6,icon_id=602,prefix="/weaponskill",range=7,skill=4,skillchain_a="Scission",skillchain_b="",skillchain_c="",targets=32},
    ['Power Slash'] = {id=49,en="Power Slash",ja="パワースラッシュ",element=6,icon_id=602,prefix="/weaponskill",range=7,skill=4,skillchain_a="Transfixion",skillchain_b="",skillchain_c="",targets=32},
    ['Frostbite'] = {id=50,en="Frostbite",ja="フロストバイト",element=1,icon_id=603,prefix="/weaponskill",range=7,skill=4,skillchain_a="Induration",skillchain_b="",skillchain_c="",targets=32},
    ['Freezebite'] = {id=51,en="Freezebite",ja="フリーズバイト",element=1,icon_id=603,prefix="/weaponskill",range=7,skill=4,skillchain_a="Induration",skillchain_b="Detonation",skillchain_c="",targets=32},
    ['Shockwave'] = {id=52,en="Shockwave",ja="ショックウェーブ",element=7,icon_id=604,prefix="/weaponskill",range=7,skill=4,skillchain_a="Reverberation",skillchain_b="",skillchain_c="",targets=32},
    ['Crescent Moon'] = {id=53,en="Crescent Moon",ja="クレセントムーン",element=6,icon_id=602,prefix="/weaponskill",range=7,skill=4,skillchain_a="Scission",skillchain_b="",skillchain_c="",targets=32},
    ['Sickle Moon'] = {id=54,en="Sickle Moon",ja="シックルムーン",element=6,icon_id=602,prefix="/weaponskill",range=7,skill=4,skillchain_a="Scission",skillchain_b="Impaction",skillchain_c="",targets=32},
    ['Spinning Slash'] = {id=55,en="Spinning Slash",ja="スピンスラッシュ",element=6,icon_id=602,prefix="/weaponskill",range=7,skill=4,skillchain_a="Fragmentation",skillchain_b="",skillchain_c="",targets=32},
    ['Ground Strike'] = {id=56,en="Ground Strike",ja="グラウンドストライク",element=6,icon_id=602,prefix="/weaponskill",range=7,skill=4,skillchain_a="Fragmentation",skillchain_b="Distortion",skillchain_c="",targets=32},
    ['Scourge'] = {id=57,en="Scourge",ja="スカージ",element=6,icon_id=602,prefix="/weaponskill",range=7,skill=4,skillchain_a="Light",skillchain_b="Fusion",skillchain_c="",targets=32},
    ['Herculean Slash'] = {id=58,en="Herculean Slash",ja="ヘラクレススラッシュ",element=1,icon_id=603,prefix="/weaponskill",range=7,skill=4,skillchain_a="Induration",skillchain_b="Impaction",skillchain_c="Detonation",targets=32},
    ['Torcleaver'] = {id=59,en="Torcleaver",ja="トアクリーバー",element=6,icon_id=602,prefix="/weaponskill",range=7,skill=4,skillchain_a="Light",skillchain_b="Distortion",skillchain_c="",targets=32},
    ['Resolution'] = {id=60,en="Resolution",ja="レゾルーション",element=6,icon_id=602,prefix="/weaponskill",range=7,skill=4,skillchain_a="Fragmentation",skillchain_b="Scission",skillchain_c="",targets=32},
    ['Dimidiation'] = {id=61,en="Dimidiation",ja="デミディエーション",element=6,icon_id=602,prefix="/weaponskill",range=7,skill=4,skillchain_a="Light",skillchain_b="Fragmentation",skillchain_c="",targets=32},
    ['Raging Axe'] = {id=64,en="Raging Axe",ja="レイジングアクス",element=6,icon_id=605,prefix="/weaponskill",range=7,skill=5,skillchain_a="Detonation",skillchain_b="Impaction",skillchain_c="",targets=32},
    ['Smash Axe'] = {id=65,en="Smash Axe",ja="スマッシュ",element=4,icon_id=606,prefix="/weaponskill",range=7,skill=5,skillchain_a="Impaction",skillchain_b="Reverberation",skillchain_c="",targets=32},
    ['Gale Axe'] = {id=66,en="Gale Axe",ja="ラファールアクス",element=2,icon_id=607,prefix="/weaponskill",range=7,skill=5,skillchain_a="Detonation",skillchain_b="",skillchain_c="",targets=32},
    ['Avalanche Axe'] = {id=67,en="Avalanche Axe",ja="アバランチアクス",element=6,icon_id=605,prefix="/weaponskill",range=7,skill=5,skillchain_a="Scission",skillchain_b="Impaction",skillchain_c="",targets=32},
    ['Spinning Axe'] = {id=68,en="Spinning Axe",ja="スピニングアクス",element=6,icon_id=605,prefix="/weaponskill",range=7,skill=5,skillchain_a="Liquefaction",skillchain_b="Scission",skillchain_c="Impaction",targets=32},
    ['Rampage'] = {id=69,en="Rampage",ja="ランページ",element=6,icon_id=605,prefix="/weaponskill",range=7,skill=5,skillchain_a="Scission",skillchain_b="",skillchain_c="",targets=32},
    ['Calamity'] = {id=70,en="Calamity",ja="カラミティ",element=6,icon_id=605,prefix="/weaponskill",range=7,skill=5,skillchain_a="Scission",skillchain_b="Impaction",skillchain_c="",targets=32},
    ['Mistral Axe'] = {id=71,en="Mistral Axe",ja="ミストラルアクス",element=6,icon_id=605,prefix="/weaponskill",range=10,skill=5,skillchain_a="Fusion",skillchain_b="",skillchain_c="",targets=32},
    ['Decimation'] = {id=72,en="Decimation",ja="デシメーション",element=6,icon_id=605,prefix="/weaponskill",range=7,skill=5,skillchain_a="Fusion",skillchain_b="Reverberation",skillchain_c="",targets=32},
    ['Onslaught'] = {id=73,en="Onslaught",ja="オンスロート",element=6,icon_id=605,prefix="/weaponskill",range=7,skill=5,skillchain_a="Darkness",skillchain_b="Gravitation",skillchain_c="",targets=32},
    ['Primal Rend'] = {id=74,en="Primal Rend",ja="プライマルレンド",element=6,icon_id=605,prefix="/weaponskill",range=7,skill=5,skillchain_a="Gravitation",skillchain_b="Reverberation",skillchain_c="",targets=32},
    ['Bora Axe'] = {id=75,en="Bora Axe",ja="ボーラアクス",element=1,icon_id=608,prefix="/weaponskill",range=10,skill=5,skillchain_a="Scission",skillchain_b="Detonation",skillchain_c="",targets=32},
    ['Cloudsplitter'] = {id=76,en="Cloudsplitter",ja="クラウドスプリッタ",element=4,icon_id=606,prefix="/weaponskill",range=7,skill=5,skillchain_a="Darkness",skillchain_b="Fragmentation",skillchain_c="",targets=32},
    ['Ruinator'] = {id=77,en="Ruinator",ja="ルイネーター",element=6,icon_id=605,prefix="/weaponskill",range=7,skill=5,skillchain_a="Distortion",skillchain_b="Detonation",skillchain_c="",targets=32},
    ['Shield Break'] = {id=80,en="Shield Break",ja="シールドブレイク",element=6,icon_id=609,prefix="/weaponskill",range=7,skill=6,skillchain_a="Impaction",skillchain_b="",skillchain_c="",targets=32},
    ['Iron Tempest'] = {id=81,en="Iron Tempest",ja="アイアンテンペスト",element=6,icon_id=609,prefix="/weaponskill",range=7,skill=6,skillchain_a="Scission",skillchain_b="",skillchain_c="",targets=32},
    ['Sturmwind'] = {id=82,en="Sturmwind",ja="シュトルムヴィント",element=6,icon_id=609,prefix="/weaponskill",range=7,skill=6,skillchain_a="Reverberation",skillchain_b="Scission",skillchain_c="",targets=32},
    ['Armor Break'] = {id=83,en="Armor Break",ja="アーマーブレイク",element=6,icon_id=609,prefix="/weaponskill",range=7,skill=6,skillchain_a="Impaction",skillchain_b="",skillchain_c="",targets=32},
    ['Keen Edge'] = {id=84,en="Keen Edge",ja="キーンエッジ",element=6,icon_id=609,prefix="/weaponskill",range=7,skill=6,skillchain_a="Compression",skillchain_b="",skillchain_c="",targets=32},
    ['Weapon Break'] = {id=85,en="Weapon Break",ja="ウェポンブレイク",element=6,icon_id=609,prefix="/weaponskill",range=7,skill=6,skillchain_a="Impaction",skillchain_b="",skillchain_c="",targets=32},
    ['Raging Rush'] = {id=86,en="Raging Rush",ja="レイジングラッシュ",element=6,icon_id=609,prefix="/weaponskill",range=7,skill=6,skillchain_a="Induration",skillchain_b="Reverberation",skillchain_c="",targets=32},
    ['Full Break'] = {id=87,en="Full Break",ja="フルブレイク",element=6,icon_id=609,prefix="/weaponskill",range=7,skill=6,skillchain_a="Distortion",skillchain_b="",skillchain_c="",targets=32},
    ['Steel Cyclone'] = {id=88,en="Steel Cyclone",ja="スチールサイクロン",element=6,icon_id=609,prefix="/weaponskill",range=7,skill=6,skillchain_a="Distortion",skillchain_b="Detonation",skillchain_c="",targets=32},
    ['Metatron Torment'] = {id=89,en="Metatron Torment",ja="メタトロントーメント",element=6,icon_id=609,prefix="/weaponskill",range=7,skill=6,skillchain_a="Light",skillchain_b="Fusion",skillchain_c="",targets=32},
    ['King\'s Justice'] = {id=90,en="King's Justice",ja="キングズジャスティス",element=6,icon_id=609,prefix="/weaponskill",range=7,skill=6,skillchain_a="Fragmentation",skillchain_b="Scission",skillchain_c="",targets=32},
    ['Fell Cleave'] = {id=91,en="Fell Cleave",ja="フェルクリーヴ",element=6,icon_id=609,prefix="/weaponskill",range=7,skill=6,skillchain_a="Scission",skillchain_b="Detonation",skillchain_c="",targets=32},
    ['Ukko\'s Fury'] = {id=92,en="Ukko's Fury",ja="ウッコフューリー",element=3,icon_id=610,prefix="/weaponskill",range=7,skill=6,skillchain_a="Light",skillchain_b="Fragmentation",skillchain_c="",targets=32},
    ['Upheaval'] = {id=93,en="Upheaval",ja="アップヒーバル",element=6,icon_id=609,prefix="/weaponskill",range=7,skill=6,skillchain_a="Fusion",skillchain_b="Compression",skillchain_c="",targets=32},
    ['Slice'] = {id=96,en="Slice",ja="スライス",element=6,icon_id=611,prefix="/weaponskill",range=7,skill=7,skillchain_a="Scission",skillchain_b="",skillchain_c="",targets=32},
    ['Dark Harvest'] = {id=97,en="Dark Harvest",ja="ダークハーベスト",element=7,icon_id=612,prefix="/weaponskill",range=7,skill=7,skillchain_a="Reverberation",skillchain_b="",skillchain_c="",targets=32},
    ['Shadow of Death'] = {id=98,en="Shadow of Death",ja="シャドーオブデス",element=7,icon_id=612,prefix="/weaponskill",range=7,skill=7,skillchain_a="Induration",skillchain_b="Reverberation",skillchain_c="",targets=32},
    ['Nightmare Scythe'] = {id=99,en="Nightmare Scythe",ja="ナイトメアサイス",element=7,icon_id=612,prefix="/weaponskill",range=7,skill=7,skillchain_a="Compression",skillchain_b="Scission",skillchain_c="",targets=32},
    ['Spinning Scythe'] = {id=100,en="Spinning Scythe",ja="スピニングサイス",element=6,icon_id=611,prefix="/weaponskill",range=7,skill=7,skillchain_a="Reverberation",skillchain_b="Scission",skillchain_c="",targets=32},
    ['Vorpal Scythe'] = {id=101,en="Vorpal Scythe",ja="ボーパルサイス",element=6,icon_id=611,prefix="/weaponskill",range=7,skill=7,skillchain_a="Transfixion",skillchain_b="Scission",skillchain_c="",targets=32},
    ['Guillotine'] = {id=102,en="Guillotine",ja="ギロティン",element=2,icon_id=613,prefix="/weaponskill",range=7,skill=7,skillchain_a="Induration",skillchain_b="",skillchain_c="",targets=32},
    ['Cross Reaper'] = {id=103,en="Cross Reaper",ja="クロスリーパー",element=6,icon_id=611,prefix="/weaponskill",range=7,skill=7,skillchain_a="Distortion",skillchain_b="",skillchain_c="",targets=32},
    ['Spiral Hell'] = {id=104,en="Spiral Hell",ja="スパイラルヘル",element=6,icon_id=611,prefix="/weaponskill",range=7,skill=7,skillchain_a="Distortion",skillchain_b="Scission",skillchain_c="",targets=32},
    ['Catastrophe'] = {id=105,en="Catastrophe",ja="カタストロフィ",element=6,icon_id=611,prefix="/weaponskill",range=7,skill=7,skillchain_a="Darkness",skillchain_b="Gravitation",skillchain_c="",targets=32},
    ['Insurgency'] = {id=106,en="Insurgency",ja="インサージェンシー",element=6,icon_id=611,prefix="/weaponskill",range=7,skill=7,skillchain_a="Fusion",skillchain_b="Compression",skillchain_c="",targets=32},
    ['Infernal Scythe'] = {id=107,en="Infernal Scythe",ja="インファナルサイズ",element=7,icon_id=612,prefix="/weaponskill",range=7,skill=7,skillchain_a="Compression",skillchain_b="Reverberation",skillchain_c="",targets=32},
    ['Quietus'] = {id=108,en="Quietus",ja="クワイタス",element=7,icon_id=612,prefix="/weaponskill",range=7,skill=7,skillchain_a="Darkness",skillchain_b="Distortion",skillchain_c="",targets=32},
    ['Entropy'] = {id=109,en="Entropy",ja="エントロピー",element=7,icon_id=612,prefix="/weaponskill",range=7,skill=7,skillchain_a="Gravitation",skillchain_b="Reverberation",skillchain_c="",targets=32},
    ['Double Thrust'] = {id=112,en="Double Thrust",ja="ダブルスラスト",element=6,icon_id=614,prefix="/weaponskill",range=7,skill=8,skillchain_a="Transfixion",skillchain_b="",skillchain_c="",targets=32},
    ['Thunder Thrust'] = {id=113,en="Thunder Thrust",ja="サンダースラスト",element=4,icon_id=615,prefix="/weaponskill",range=7,skill=8,skillchain_a="Transfixion",skillchain_b="Impaction",skillchain_c="",targets=32},
    ['Raiden Thrust'] = {id=114,en="Raiden Thrust",ja="ライデンスラスト",element=4,icon_id=615,prefix="/weaponskill",range=7,skill=8,skillchain_a="Transfixion",skillchain_b="Impaction",skillchain_c="",targets=32},
    ['Leg Sweep'] = {id=115,en="Leg Sweep",ja="足払い",element=4,icon_id=615,prefix="/weaponskill",range=7,skill=8,skillchain_a="Impaction",skillchain_b="",skillchain_c="",targets=32},
    ['Penta Thrust'] = {id=116,en="Penta Thrust",ja="ペンタスラスト",element=6,icon_id=614,prefix="/weaponskill",range=7,skill=8,skillchain_a="Compression",skillchain_b="",skillchain_c="",targets=32},
    ['Vorpal Thrust'] = {id=117,en="Vorpal Thrust",ja="ボーパルスラスト",element=6,icon_id=614,prefix="/weaponskill",range=7,skill=8,skillchain_a="Reverberation",skillchain_b="Transfixion",skillchain_c="",targets=32},
    ['Skewer'] = {id=118,en="Skewer",ja="スキュアー",element=6,icon_id=614,prefix="/weaponskill",range=7,skill=8,skillchain_a="Transfixion",skillchain_b="Impaction",skillchain_c="",targets=32},
    ['Wheeling Thrust'] = {id=119,en="Wheeling Thrust",ja="大車輪",element=6,icon_id=614,prefix="/weaponskill",range=7,skill=8,skillchain_a="Fusion",skillchain_b="",skillchain_c="",targets=32},
    ['Impulse Drive'] = {id=120,en="Impulse Drive",ja="インパルスドライヴ",element=6,icon_id=614,prefix="/weaponskill",range=7,skill=8,skillchain_a="Gravitation",skillchain_b="Induration",skillchain_c="",targets=32},
    ['Geirskogul'] = {id=121,en="Geirskogul",ja="ゲイルスコグル",element=6,icon_id=614,prefix="/weaponskill",range=7,skill=8,skillchain_a="Light",skillchain_b="Distortion",skillchain_c="",targets=32},
    ['Drakesbane'] = {id=122,en="Drakesbane",ja="雲蒸竜変",element=6,icon_id=614,prefix="/weaponskill",range=7,skill=8,skillchain_a="Fusion",skillchain_b="Transfixion",skillchain_c="",targets=32},
    ['Sonic Thrust'] = {id=123,en="Sonic Thrust",ja="ソニックスラスト",element=6,icon_id=614,prefix="/weaponskill",range=7,skill=8,skillchain_a="Transfixion",skillchain_b="Scission",skillchain_c="",targets=32},
    ['Camlann\'s Torment'] = {id=124,en="Camlann's Torment",ja="カムラン",element=6,icon_id=614,prefix="/weaponskill",range=7,skill=8,skillchain_a="Light",skillchain_b="Fragmentation",skillchain_c="",targets=32},
    ['Stardiver'] = {id=125,en="Stardiver",ja="スターダイバー",element=3,icon_id=616,prefix="/weaponskill",range=7,skill=8,skillchain_a="Gravitation",skillchain_b="Transfixion",skillchain_c="",targets=32},
    ['Blade: Rin'] = {id=128,en="Blade: Rin",ja="臨",element=6,icon_id=617,prefix="/weaponskill",range=7,skill=9,skillchain_a="Transfixion",skillchain_b="",skillchain_c="",targets=32},
    ['Blade: Retsu'] = {id=129,en="Blade: Retsu",ja="烈",element=1,icon_id=618,prefix="/weaponskill",range=7,skill=9,skillchain_a="Scission",skillchain_b="",skillchain_c="",targets=32},
    ['Blade: Teki'] = {id=130,en="Blade: Teki",ja="滴",element=5,icon_id=619,prefix="/weaponskill",range=7,skill=9,skillchain_a="Reverberation",skillchain_b="",skillchain_c="",targets=32},
    ['Blade: To'] = {id=131,en="Blade: To",ja="凍",element=1,icon_id=618,prefix="/weaponskill",range=7,skill=9,skillchain_a="Induration",skillchain_b="Detonation",skillchain_c="",targets=32},
    ['Blade: Chi'] = {id=132,en="Blade: Chi",ja="地",element=3,icon_id=620,prefix="/weaponskill",range=7,skill=9,skillchain_a="Impaction",skillchain_b="Transfixion",skillchain_c="",targets=32},
    ['Blade: Ei'] = {id=133,en="Blade: Ei",ja="影",element=7,icon_id=621,prefix="/weaponskill",range=7,skill=9,skillchain_a="Compression",skillchain_b="",skillchain_c="",targets=32},
    ['Blade: Jin'] = {id=134,en="Blade: Jin",ja="迅",element=6,icon_id=617,prefix="/weaponskill",range=7,skill=9,skillchain_a="Impaction",skillchain_b="Detonation",skillchain_c="",targets=32},
    ['Blade: Ten'] = {id=135,en="Blade: Ten",ja="天",element=6,icon_id=617,prefix="/weaponskill",range=7,skill=9,skillchain_a="Gravitation",skillchain_b="",skillchain_c="",targets=32},
    ['Blade: Ku'] = {id=136,en="Blade: Ku",ja="空",element=6,icon_id=617,prefix="/weaponskill",range=7,skill=9,skillchain_a="Gravitation",skillchain_b="Transfixion",skillchain_c="",targets=32},
    ['Blade: Metsu'] = {id=137,en="Blade: Metsu",ja="生者必滅",element=6,icon_id=617,prefix="/weaponskill",range=7,skill=9,skillchain_a="Darkness",skillchain_b="Fragmentation",skillchain_c="",targets=32},
    ['Blade: Kamu'] = {id=138,en="Blade: Kamu",ja="カムハブリ",element=3,icon_id=620,prefix="/weaponskill",range=7,skill=9,skillchain_a="Fragmentation",skillchain_b="Compression",skillchain_c="",targets=32},
    ['Blade: Yu'] = {id=139,en="Blade: Yu",ja="湧",element=5,icon_id=619,prefix="/weaponskill",range=7,skill=9,skillchain_a="Reverberation",skillchain_b="Scission",skillchain_c="",targets=32},
    ['Blade: Hi'] = {id=140,en="Blade: Hi",ja="秘",element=6,icon_id=617,prefix="/weaponskill",range=7,skill=9,skillchain_a="Darkness",skillchain_b="Gravitation",skillchain_c="",targets=32},
    ['Blade: Shun'] = {id=141,en="Blade: Shun",ja="瞬",element=6,icon_id=617,prefix="/weaponskill",range=7,skill=9,skillchain_a="Fusion",skillchain_b="Impaction",skillchain_c="",targets=32},
    ['Tachi: Enpi'] = {id=144,en="Tachi: Enpi",ja="壱之太刀・燕飛",element=6,icon_id=622,prefix="/weaponskill",range=7,skill=10,skillchain_a="Transfixion",skillchain_b="Scission",skillchain_c="",targets=32},
    ['Tachi: Hobaku'] = {id=145,en="Tachi: Hobaku",ja="弐之太刀・鋒縛",element=4,icon_id=623,prefix="/weaponskill",range=7,skill=10,skillchain_a="Induration",skillchain_b="",skillchain_c="",targets=32},
    ['Tachi: Goten'] = {id=146,en="Tachi: Goten",ja="参之太刀・轟天",element=4,icon_id=623,prefix="/weaponskill",range=7,skill=10,skillchain_a="Transfixion",skillchain_b="Impaction",skillchain_c="",targets=32},
    ['Tachi: Kagero'] = {id=147,en="Tachi: Kagero",ja="四之太刀・陽炎",element=0,icon_id=624,prefix="/weaponskill",range=7,skill=10,skillchain_a="Liquefaction",skillchain_b="",skillchain_c="",targets=32},
    ['Tachi: Jinpu'] = {id=148,en="Tachi: Jinpu",ja="五之太刀・陣風",element=2,icon_id=625,prefix="/weaponskill",range=7,skill=10,skillchain_a="Scission",skillchain_b="Detonation",skillchain_c="",targets=32},
    ['Tachi: Koki'] = {id=149,en="Tachi: Koki",ja="六之太刀・光輝",element=6,icon_id=622,prefix="/weaponskill",range=7,skill=10,skillchain_a="Reverberation",skillchain_b="Impaction",skillchain_c="",targets=32},
    ['Tachi: Yukikaze'] = {id=150,en="Tachi: Yukikaze",ja="七之太刀・雪風",element=7,icon_id=626,prefix="/weaponskill",range=7,skill=10,skillchain_a="Induration",skillchain_b="Detonation",skillchain_c="",targets=32},
    ['Tachi: Gekko'] = {id=151,en="Tachi: Gekko",ja="八之太刀・月光",element=2,icon_id=625,prefix="/weaponskill",range=7,skill=10,skillchain_a="Distortion",skillchain_b="Reverberation",skillchain_c="",targets=32},
    ['Tachi: Kasha'] = {id=152,en="Tachi: Kasha",ja="九之太刀・花車",element=1,icon_id=627,prefix="/weaponskill",range=7,skill=10,skillchain_a="Fusion",skillchain_b="Compression",skillchain_c="",targets=32},
    ['Tachi: Kaiten'] = {id=153,en="Tachi: Kaiten",ja="零之太刀・回天",element=6,icon_id=622,prefix="/weaponskill",range=7,skill=10,skillchain_a="Light",skillchain_b="Fragmentation",skillchain_c="",targets=32},
    ['Tachi: Rana'] = {id=154,en="Tachi: Rana",ja="十之太刀・乱鴉",element=6,icon_id=622,prefix="/weaponskill",range=7,skill=10,skillchain_a="Gravitation",skillchain_b="Induration",skillchain_c="",targets=32},
    ['Tachi: Ageha'] = {id=155,en="Tachi: Ageha",ja="十一之太刀・鳳蝶",element=2,icon_id=625,prefix="/weaponskill",range=7,skill=10,skillchain_a="Compression",skillchain_b="Scission",skillchain_c="",targets=32},
    ['Tachi: Fudo'] = {id=156,en="Tachi: Fudo",ja="祖之太刀・不動",element=6,icon_id=622,prefix="/weaponskill",range=7,skill=10,skillchain_a="Light",skillchain_b="Distortion",skillchain_c="",targets=32},
    ['Tachi: Shoha'] = {id=157,en="Tachi: Shoha",ja="十二之太刀・照破",element=6,icon_id=622,prefix="/weaponskill",range=7,skill=10,skillchain_a="Fragmentation",skillchain_b="Compression",skillchain_c="",targets=32},
    ['Tachi: Suikawar'] = {id=158,en="Tachi: Suikawari",ja="盛夏之太刀・西瓜割",element=6,icon_id=622,prefix="/weaponskill",range=7,targets=32},
    ['Shining Strike'] = {id=160,en="Shining Strike",ja="シャインストライク",element=6,icon_id=628,prefix="/weaponskill",range=7,skill=11,skillchain_a="Impaction",skillchain_b="",skillchain_c="",targets=32},
    ['Seraph Strike'] = {id=161,en="Seraph Strike",ja="セラフストライク",element=6,icon_id=628,prefix="/weaponskill",range=7,skill=11,skillchain_a="Impaction",skillchain_b="",skillchain_c="",targets=32},
    ['Brainshaker'] = {id=162,en="Brainshaker",ja="ブレインシェイカー",element=4,icon_id=629,prefix="/weaponskill",range=7,skill=11,skillchain_a="Reverberation",skillchain_b="",skillchain_c="",targets=32},
    ['Starlight'] = {id=163,en="Starlight",ja="スターライト",element=6,icon_id=628,prefix="/weaponskill",range=7,skill=11,skillchain_a="",skillchain_b="",skillchain_c="",targets=1},
    ['Moonlight'] = {id=164,en="Moonlight",ja="ムーンライト",element=6,icon_id=628,prefix="/weaponskill",range=7,skill=11,skillchain_a="",skillchain_b="",skillchain_c="",targets=1},
    ['Skullbreaker'] = {id=165,en="Skullbreaker",ja="スカルブレイカー",element=0,icon_id=630,prefix="/weaponskill",range=7,skill=11,skillchain_a="Induration",skillchain_b="Reverberation",skillchain_c="",targets=32},
    ['True Strike'] = {id=166,en="True Strike",ja="トゥルーストライク",element=6,icon_id=628,prefix="/weaponskill",range=7,skill=11,skillchain_a="Detonation",skillchain_b="Impaction",skillchain_c="",targets=32},
    ['Judgment'] = {id=167,en="Judgment",ja="ジャッジメント",element=6,icon_id=628,prefix="/weaponskill",range=7,skill=11,skillchain_a="Impaction",skillchain_b="",skillchain_c="",targets=32},
    ['Hexa Strike'] = {id=168,en="Hexa Strike",ja="ヘキサストライク",element=6,icon_id=628,prefix="/weaponskill",range=7,skill=11,skillchain_a="Fusion",skillchain_b="",skillchain_c="",targets=32},
    ['Black Halo'] = {id=169,en="Black Halo",ja="ブラックヘイロー",element=6,icon_id=628,prefix="/weaponskill",range=7,skill=11,skillchain_a="Fragmentation",skillchain_b="Compression",skillchain_c="",targets=32},
    ['Randgrith'] = {id=170,en="Randgrith",ja="ランドグリース",element=6,icon_id=628,prefix="/weaponskill",range=7,skill=11,skillchain_a="Light",skillchain_b="Fragmentation",skillchain_c="",targets=32},
    ['Mystic Boon'] = {id=171,en="Mystic Boon",ja="ミスティックブーン",element=6,icon_id=628,prefix="/weaponskill",range=7,skill=11,skillchain_a="",skillchain_b="",skillchain_c="",targets=32},
    ['Flash Nova'] = {id=172,en="Flash Nova",ja="フラッシュノヴァ",element=6,icon_id=628,prefix="/weaponskill",range=7,skill=11,skillchain_a="Induration",skillchain_b="Reverberation",skillchain_c="",targets=32},
    ['Dagan'] = {id=173,en="Dagan",ja="ダガン",element=6,icon_id=628,prefix="/weaponskill",range=7,skill=11,skillchain_a="",skillchain_b="",skillchain_c="",targets=1},
    ['Realmrazer'] = {id=174,en="Realmrazer",ja="レルムレイザー",element=6,icon_id=628,prefix="/weaponskill",range=7,skill=11,skillchain_a="Fusion",skillchain_b="Impaction",skillchain_c="",targets=32},
    ['Exudation'] = {id=175,en="Exudation",ja="エクズデーション",element=6,icon_id=628,prefix="/weaponskill",range=7,skill=11,skillchain_a="Darkness",skillchain_b="Fragmentation",skillchain_c="",targets=32},
    ['Heavy Swing'] = {id=176,en="Heavy Swing",ja="ヘヴィスイング",element=6,icon_id=631,prefix="/weaponskill",range=7,skill=12,skillchain_a="Impaction",skillchain_b="",skillchain_c="",targets=32},
    ['Rock Crusher'] = {id=177,en="Rock Crusher",ja="ロッククラッシャー",element=3,icon_id=632,prefix="/weaponskill",range=7,skill=12,skillchain_a="Impaction",skillchain_b="",skillchain_c="",targets=32},
    ['Earth Crusher'] = {id=178,en="Earth Crusher",ja="アースクラッシャー",element=3,icon_id=632,prefix="/weaponskill",range=7,skill=12,skillchain_a="Detonation",skillchain_b="Impaction",skillchain_c="",targets=32},
    ['Starburst'] = {id=179,en="Starburst",ja="スターバースト",element=6,icon_id=631,prefix="/weaponskill",range=7,skill=12,skillchain_a="Compression",skillchain_b="Reverberation",skillchain_c="",targets=32},
    ['Sunburst'] = {id=180,en="Sunburst",ja="サンバースト",element=6,icon_id=631,prefix="/weaponskill",range=7,skill=12,skillchain_a="Compression",skillchain_b="Reverberation",skillchain_c="",targets=32},
    ['Shell Crusher'] = {id=181,en="Shell Crusher",ja="シェルクラッシャー",element=6,icon_id=631,prefix="/weaponskill",range=7,skill=12,skillchain_a="Detonation",skillchain_b="",skillchain_c="",targets=32},
    ['Full Swing'] = {id=182,en="Full Swing",ja="フルスイング",element=6,icon_id=631,prefix="/weaponskill",range=7,skill=12,skillchain_a="Liquefaction",skillchain_b="Impaction",skillchain_c="",targets=32},
    ['Spirit Taker'] = {id=183,en="Spirit Taker",ja="スピリットテーカー",element=6,icon_id=631,prefix="/weaponskill",range=7,skill=12,skillchain_a="",skillchain_b="",skillchain_c="",targets=32},
    ['Retribution'] = {id=184,en="Retribution",ja="レトリビューション",element=6,icon_id=631,prefix="/weaponskill",range=7,skill=12,skillchain_a="Gravitation",skillchain_b="Reverberation",skillchain_c="",targets=32},
    ['Gate of Tartarus'] = {id=185,en="Gate of Tartarus",ja="タルタロスゲート",element=6,icon_id=631,prefix="/weaponskill",range=7,skill=12,skillchain_a="Darkness",skillchain_b="Distortion",skillchain_c="",targets=32},
    ['Vidohunir'] = {id=186,en="Vidohunir",ja="ヴィゾフニル",element=7,icon_id=633,prefix="/weaponskill",range=7,skill=12,skillchain_a="Fragmentation",skillchain_b="Distortion",skillchain_c="",targets=32},
    ['Garland of Bliss'] = {id=187,en="Garland of Bliss",ja="ガーランドオブブリス",element=6,icon_id=631,prefix="/weaponskill",range=7,skill=12,skillchain_a="Fusion",skillchain_b="Reverberation",skillchain_c="",targets=32},
    ['Omniscience'] = {id=188,en="Omniscience",ja="オムニシエンス",element=7,icon_id=633,prefix="/weaponskill",range=7,skill=12,skillchain_a="Gravitation",skillchain_b="Transfixion",skillchain_c="",targets=32},
    ['Cataclysm'] = {id=189,en="Cataclysm",ja="カタクリスム",element=7,icon_id=633,prefix="/weaponskill",range=7,skill=12,skillchain_a="Compression",skillchain_b="Reverberation",skillchain_c="",targets=32},
    ['Myrkr'] = {id=190,en="Myrkr",ja="ミルキル",element=7,icon_id=633,prefix="/weaponskill",range=7,skill=12,skillchain_a="",skillchain_b="",skillchain_c="",targets=1},
    ['Shattersoul'] = {id=191,en="Shattersoul",ja="シャッターソウル",element=4,icon_id=634,prefix="/weaponskill",range=7,skill=12,skillchain_a="Gravitation",skillchain_b="Induration",skillchain_c="",targets=32},
    ['Flaming Arrow'] = {id=192,en="Flaming Arrow",ja="フレイミングアロー",element=0,icon_id=635,prefix="/weaponskill",range=21,skill=25,skillchain_a="Liquefaction",skillchain_b="Transfixion",skillchain_c="",targets=32},
    ['Piercing Arrow'] = {id=193,en="Piercing Arrow",ja="ピアシングアロー",element=2,icon_id=636,prefix="/weaponskill",range=21,skill=25,skillchain_a="Reverberation",skillchain_b="Transfixion",skillchain_c="",targets=32},
    ['Dulling Arrow'] = {id=194,en="Dulling Arrow",ja="ダリングアロー",element=0,icon_id=635,prefix="/weaponskill",range=21,skill=25,skillchain_a="Liquefaction",skillchain_b="Transfixion",skillchain_c="",targets=32},
    ['Sidewinder'] = {id=196,en="Sidewinder",ja="サイドワインダー",element=6,icon_id=637,prefix="/weaponskill",range=21,skill=25,skillchain_a="Reverberation",skillchain_b="Transfixion",skillchain_c="Detonation",targets=32},
    ['Blast Arrow'] = {id=197,en="Blast Arrow",ja="ブラストアロー",element=6,icon_id=637,prefix="/weaponskill",range=7,skill=25,skillchain_a="Induration",skillchain_b="Transfixion",skillchain_c="",targets=32},
    ['Arching Arrow'] = {id=198,en="Arching Arrow",ja="アーチングアロー",element=6,icon_id=637,prefix="/weaponskill",range=21,skill=25,skillchain_a="Fusion",skillchain_b="",skillchain_c="",targets=32},
    ['Empyreal Arrow'] = {id=199,en="Empyreal Arrow",ja="エンピリアルアロー",element=6,icon_id=637,prefix="/weaponskill",range=21,skill=25,skillchain_a="Fusion",skillchain_b="Transfixion",skillchain_c="",targets=32},
    ['Namas Arrow'] = {id=200,en="Namas Arrow",ja="南無八幡",element=6,icon_id=637,prefix="/weaponskill",range=21,skill=25,skillchain_a="Light",skillchain_b="Distortion",skillchain_c="",targets=32},
    ['Refulgent Arrow'] = {id=201,en="Refulgent Arrow",ja="リフルジェントアロー",element=6,icon_id=637,prefix="/weaponskill",range=21,skill=25,skillchain_a="Reverberation",skillchain_b="Transfixion",skillchain_c="",targets=32},
    ['Jishnu\'s Radiance'] = {id=202,en="Jishnu's Radiance",ja="ジシュヌの光輝",element=6,icon_id=637,prefix="/weaponskill",range=21,skill=25,skillchain_a="Light",skillchain_b="Fusion",skillchain_c="",targets=32},
    ['Apex Arrow'] = {id=203,en="Apex Arrow",ja="エイペクスアロー",element=6,icon_id=637,prefix="/weaponskill",range=21,skill=25,skillchain_a="Fragmentation",skillchain_b="Transfixion",skillchain_c="",targets=32},
    ['Hot Shot'] = {id=208,en="Hot Shot",ja="ホットショット",element=0,icon_id=638,prefix="/weaponskill",range=21,skill=26,skillchain_a="Reverberation",skillchain_b="Transfixion",skillchain_c="",targets=32},
    ['Split Shot'] = {id=209,en="Split Shot",ja="スプリットショット",element=2,icon_id=639,prefix="/weaponskill",range=21,skill=26,skillchain_a="Reverberation",skillchain_b="Transfixion",skillchain_c="",targets=32},
    ['Sniper Shot'] = {id=210,en="Sniper Shot",ja="スナイパーショット",element=0,icon_id=638,prefix="/weaponskill",range=21,skill=26,skillchain_a="Liquefaction",skillchain_b="Transfixion",skillchain_c="",targets=32},
    ['Slug Shot'] = {id=212,en="Slug Shot",ja="スラッグショット",element=6,icon_id=640,prefix="/weaponskill",range=21,skill=26,skillchain_a="Reverberation",skillchain_b="Transfixion",skillchain_c="Detonation",targets=32},
    ['Blast Shot'] = {id=213,en="Blast Shot",ja="ブラストショット",element=6,icon_id=640,prefix="/weaponskill",range=7,skill=26,skillchain_a="Induration",skillchain_b="Transfixion",skillchain_c="",targets=32},
    ['Heavy Shot'] = {id=214,en="Heavy Shot",ja="ヘヴィショット",element=6,icon_id=640,prefix="/weaponskill",range=21,skill=26,skillchain_a="Fusion",skillchain_b="",skillchain_c="",targets=32},
    ['Detonator'] = {id=215,en="Detonator",ja="デトネーター",element=6,icon_id=640,prefix="/weaponskill",range=21,skill=26,skillchain_a="Fusion",skillchain_b="Transfixion",skillchain_c="",targets=32},
    ['Coronach'] = {id=216,en="Coronach",ja="カラナック",element=6,icon_id=640,prefix="/weaponskill",range=21,skill=26,skillchain_a="Darkness",skillchain_b="Fragmentation",skillchain_c="",targets=32},
    ['Trueflight'] = {id=217,en="Trueflight",ja="トゥルーフライト",element=6,icon_id=640,prefix="/weaponskill",range=21,skill=26,skillchain_a="Fragmentation",skillchain_b="Scission",skillchain_c="",targets=32},
    ['Leaden Salute'] = {id=218,en="Leaden Salute",ja="レデンサリュート",element=7,icon_id=641,prefix="/weaponskill",range=21,skill=26,skillchain_a="Gravitation",skillchain_b="Transfixion",skillchain_c="",targets=32},
    ['Numbing Shot'] = {id=219,en="Numbing Shot",ja="ナビングショット",element=1,icon_id=642,prefix="/weaponskill",range=7,skill=26,skillchain_a="Induration",skillchain_b="Impaction",skillchain_c="Detonation",targets=32},
    ['Wildfire'] = {id=220,en="Wildfire",ja="ワイルドファイア",element=0,icon_id=638,prefix="/weaponskill",range=21,skill=26,skillchain_a="Darkness",skillchain_b="Gravitation",skillchain_c="",targets=32},
    ['Last Stand'] = {id=221,en="Last Stand",ja="ラストスタンド",element=6,icon_id=640,prefix="/weaponskill",range=21,skill=26,skillchain_a="Fusion",skillchain_b="Reverberation",skillchain_c="",targets=32},
    ['Exenterator'] = {id=224,en="Exenterator",ja="エクゼンテレター",element=3,icon_id=643,prefix="/weaponskill",range=7,skill=2,skillchain_a="Fragmentation",skillchain_b="Scission",skillchain_c="",targets=32},
    ['Chant du Cygne'] = {id=225,en="Chant du Cygne",ja="シャンデュシニュ",element=6,icon_id=644,prefix="/weaponskill",range=7,skill=3,skillchain_a="Light",skillchain_b="Distortion",skillchain_c="",targets=32},
    ['Requiescat'] = {id=226,en="Requiescat",ja="レクイエスカット",element=6,icon_id=644,prefix="/weaponskill",range=7,skill=3,skillchain_a="Gravitation",skillchain_b="Scission",skillchain_c="",targets=32},
    ['Knights of Rotund'] = {id=227,en="Knights of Rotund",ja="ナイスオブラウンド",element=6,icon_id=598,prefix="/weaponskill",range=7,targets=32},
    ['Final Paradise'] = {id=228,en="Final Paradise",ja="ファイナルパラダイス",element=6,icon_id=590,prefix="/weaponskill",range=7,targets=32},
    ['Uriel Blade'] = {id=238,en="Uriel Blade",ja="ウリエルブレード",element=6,icon_id=645,prefix="/weaponskill",range=7,skill=2,skillchain_a="",skillchain_b="",skillchain_c="",targets=32},
    ['Glory Slash'] = {id=239,en="Glory Slash",ja="グローリースラッシュ",element=4,icon_id=646,prefix="/weaponskill",range=7,skill=2,skillchain_a="",skillchain_b="",skillchain_c="",targets=32},
    ['Tartarus Torpor'] = {id=240,en="Tartarus Torpor",ja="タルタロストーパー",element=7,icon_id=647,prefix="/weaponskill",range=7,skill=12,skillchain_a="",skillchain_b="",skillchain_c="",targets=32},
    ['Netherspikes'] = {id=241,en="Netherspikes",ja="剣山獄",element=6,icon_id=46,prefix="/weaponskill",range=7,skillchain_a="",skillchain_b="",skillchain_c="",targets=32},
    ['Carnal Nightmare'] = {id=242,en="Carnal Nightmare",ja="白昼夢",element=6,icon_id=46,prefix="/weaponskill",range=7,skillchain_a="",skillchain_b="",skillchain_c="",targets=32},
    ['Aegis Schism'] = {id=243,en="Aegis Schism",ja="破鎧陣",element=6,icon_id=46,prefix="/weaponskill",range=7,skillchain_a="",skillchain_b="",skillchain_c="",targets=32},
    ['Dancing Chains'] = {id=244,en="Dancing Chains",ja="舞空鎖",element=6,icon_id=46,prefix="/weaponskill",range=7,skillchain_a="",skillchain_b="",skillchain_c="",targets=32},
    ['Barbed Crescent'] = {id=245,en="Barbed Crescent",ja="偃月刃",element=6,icon_id=46,prefix="/weaponskill",range=11,skillchain_a="",skillchain_b="",skillchain_c="",targets=32},
    ['Shackled Fists'] = {id=246,en="Shackled Fists",ja="連環拳",element=6,icon_id=46,prefix="/weaponskill",range=7,skillchain_a="",skillchain_b="",skillchain_c="",targets=32},
    ['Foxfire'] = {id=247,en="Foxfire",ja="跳狐斬",element=6,icon_id=46,prefix="/weaponskill",range=7,skillchain_a="",skillchain_b="",skillchain_c="",targets=32},
    ['Grim Halo'] = {id=248,en="Grim Halo",ja="輪天殺",element=6,icon_id=46,prefix="/weaponskill",range=7,skillchain_a="",skillchain_b="",skillchain_c="",targets=32},
    ['Netherspikes'] = {id=249,en="Netherspikes",ja="剣山獄",element=6,icon_id=46,prefix="/weaponskill",range=7,skillchain_a="",skillchain_b="",skillchain_c="",targets=32},
    ['Carnal Nightmare'] = {id=250,en="Carnal Nightmare",ja="白昼夢",element=6,icon_id=46,prefix="/weaponskill",range=7,skillchain_a="",skillchain_b="",skillchain_c="",targets=32},
    ['Aegis Schism"'] = {id=251,en="Aegis Schism",ja="破鎧陣",element=6,icon_id=46,prefix="/weaponskill",range=7,skillchain_a="",skillchain_b="",skillchain_c="",targets=32},
    ['Dancing Chains'] = {id=252,en="Dancing Chains",ja="舞空鎖",element=6,icon_id=46,prefix="/weaponskill",range=7,skillchain_a="",skillchain_b="",skillchain_c="",targets=32},
    ['Barbed Crescent'] = {id=253,en="Barbed Crescent",ja="偃月刃",element=6,icon_id=46,prefix="/weaponskill",range=11,skillchain_a="",skillchain_b="",skillchain_c="",targets=32},
    ['Vulcan Shot'] = {id=254,en="Vulcan Shot",ja="バルカンショット",element=6,icon_id=46,prefix="/weaponskill",range=21,skillchain_a="",skillchain_b="",skillchain_c="",targets=32},
    ['Dimensional Death'] = {id=255,en="Dimensional Death",ja="次元殺",element=6,icon_id=46,prefix="/weaponskill",range=7,skillchain_a="",skillchain_b="",skillchain_c="",targets=32},
    ['Oshala'] = {id=235,en="Oshala",ja="オシャラ",element=6,icon_id=631,prefix="/weaponskill",range=2,skill=12,skillchain_a="Induration",skillchain_b="Reverberation",skillchain_c="Fusion",targets=32},
    ['Dagda'] = {id=234,en="Dagda",ja="ダグダ",element=6,icon_id=628,prefix="/weaponskill",range=2,skill=11,skillchain_a="Transfixion",skillchain_b="Scission",skillchain_c="Gravitation",targets=32},
    ['Imperator'] = {id=233,en="Imperator",ja="インペラトル",element=6,icon_id=598,prefix="/weaponskill",range=2,skill=3,skillchain_a="Detonation",skillchain_b="Compression",skillchain_c="Distortion",targets=32},
    ['Ruthless Stroke'] = {id=232,en="Ruthless Stroke",ja="ルースレスストローク",element=6,icon_id=597,prefix="/weaponskill",range=2,skill=2,skillchain_a="Liquefaction",skillchain_b="Impaction",skillchain_c="Fragmentation",targets=32},
    ['Maru Kala'] = {id=231,en="Maru Kala",ja="マルカラ",element=6,icon_id=590,prefix="/weaponskill",range=2,skill=1,skillchain_a="Detonation",skillchain_b="Compression",skillchain_c="Distortion",targets=32},
    ['Dragon Blow'] = {id=230,en="Dragon Blow",ja="ドラゴンブロウ",element=6,icon_id=590,prefix="/weaponskill",range=2,skill=1,skillchain_a="Distortion",skillchain_b="",skillchain_c="",targets=32},
    ['Fast Blade II'] = {id=229,en="Fast Blade II",ja="ファストブレードII",element=6,icon_id=598,prefix="/weaponskill",range=2,skill=3,skillchain_a="Fusion",skillchain_b="",skillchain_c="",targets=32},
    ['Terminus'] = {id=222,en="Terminus",ja="ジ・エンド",element=6,icon_id=640,prefix="/weaponskill",range=12,skill=26,skillchain_a="Induration",skillchain_b="Reverberation",skillchain_c="Fusion",targets=32},
    ['Sarv'] = {id=204,en="Sarv",ja="シャルヴ",element=6,icon_id=637,prefix="/weaponskill",range=12,skill=25,skillchain_a="Transfixion",skillchain_b="Scission",skillchain_c="Gravitation",targets=32},
    ['Tachi: Mumei'] = {id=159,en="Tachi: Mumei",ja="絶之太刀・無名",element=6,icon_id=622,prefix="/weaponskill",range=2,skill=10,skillchain_a="Detonation",skillchain_b="Compression",skillchain_c="Distortion",targets=32},
    ['Zesho Meppo'] = {id=142,en="Zesho Meppo",ja="是生滅法",element=6,icon_id=617,prefix="/weaponskill",range=2,skill=9,skillchain_a="Induration",skillchain_b="Reverberation",skillchain_c="Fusion",targets=32},
    ['Diarmuid'] = {id=126,en="Diarmuid",ja="ダーマット",element=6,icon_id=614,prefix="/weaponskill",range=2,skill=8,skillchain_a="Transfixion",skillchain_b="Scission",skillchain_c="Gravitation",targets=32},
    ['Origin'] = {id=110,en="Origin",ja="ジ・オリジン",element=6,icon_id=611,prefix="/weaponskill",range=2,skill=7,skillchain_a="Induration",skillchain_b="Reverberation",skillchain_c="Fusion",targets=32},
    ['Disaster'] = {id=94,en="Disaster",ja="ディザスター",element=6,icon_id=609,prefix="/weaponskill",range=2,skill=6,skillchain_a="Transfixion",skillchain_b="Scission",skillchain_c="Gravitation",targets=32},
    ['Blitz'] = {id=78,en="Blitz",ja="ブリッツ",element=6,icon_id=605,prefix="/weaponskill",range=2,skill=5,skillchain_a="Liquefaction",skillchain_b="Impaction",skillchain_c="Fragmentation",targets=32},
    ['Fimbulvetr'] = {id=62,en="Fimbulvetr",ja="フィンブルヴェト",element=6,icon_id=602,prefix="/weaponskill",range=2,skill=4,skillchain_a="Detonation",skillchain_b="Compression",skillchain_c="Distortion",targets=32},

}, {"id", "en", "ja", "element", "icon_id", "prefix", "range", "skill", "skillchain_a", "skillchain_b", "skillchain_c", "targets"}

--[[
Copyright © 2013-2018, Windower
All rights reserved.

Redistribution and use in source and binary forms, with or without modification, are permitted provided that the following conditions are met:

    * Redistributions of source code must retain the above copyright notice, this list of conditions and the following disclaimer.
    * Redistributions in binary form must reproduce the above copyright notice, this list of conditions and the following disclaimer in the documentation and/or other materials provided with the distribution.
    * Neither the name of Windower nor the names of its contributors may be used to endorse or promote products derived from this software without specific prior written permission.

THIS SOFTWARE IS PROVIDED BY THE COPYRIGHT HOLDERS AND CONTRIBUTORS "AS IS" AND ANY EXPRESS OR IMPLIED WARRANTIES, INCLUDING, BUT NOT LIMITED TO, THE IMPLIED WARRANTIES OF MERCHANTABILITY AND FITNESS FOR A PARTICULAR PURPOSE ARE DISCLAIMED. IN NO EVENT SHALL Windower BE LIABLE FOR ANY DIRECT, INDIRECT, INCIDENTAL, SPECIAL, EXEMPLARY, OR CONSEQUENTIAL DAMAGES (INCLUDING, BUT NOT LIMITED TO, PROCUREMENT OF SUBSTITUTE GOODS OR SERVICES; LOSS OF USE, DATA, OR PROFITS; OR BUSINESS INTERRUPTION) HOWEVER CAUSED AND ON ANY THEORY OF LIABILITY, WHETHER IN CONTRACT, STRICT LIABILITY, OR TORT (INCLUDING NEGLIGENCE OR OTHERWISE) ARISING IN ANY WAY OUT OF THE USE OF THIS SOFTWARE, EVEN IF ADVISED OF THE POSSIBILITY OF SUCH DAMAGE.
]]
